---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:system:observabilityapps
  labels:
    rbac.gardener.cloud/aggregate-to-project-member: "true"
    rbac.gardener.cloud/aggregate-to-project-admin: "true"
    rbac.gardener.cloud/aggregate-to-project-viewer: "true"
rules:
  - apiGroups: ["authorization.extensions.gardener.cloud"]
    resources:
      - observabilityapps/plutono
      - observabilityapps/prometheus
    verbs: ["get", "create"]
