---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+09aXPjNrL5zF+BJ+9WZmZN6hjLzlNVPji2N+vNHC7LM3mvUqkURUISY4pgCFK24sz77a8bBwkeumyP51ihpmY0BNDobnQ3unGywPdsN4657bEoTVgY0qT9zeOmDqSjfl/8C6n6r/jdPej3u0cH3X6v902n+/IQ/iH9R8ajMWU8dRNCvkkYS1eVW5f/hSbW1P/OlIazYBKxhD5GG9jBhwcHS/u/f9Cv9H//6LDzDek8RuPr0n94/++RCzdNaRJxkjIi+5zcTGlERlkQ+kE0IbHrXbsTyh1rj1xNA054FscsSeEHyElIJiEbkZmbelMovU8SGrppMKdQL50a393IBwARnUAui8izOKHj4Jb65CaAcv/13CFvo3BBWCRqIkokpgkJg4g6lnM6/G2YAm4A4oTNZgDg/cmQ+EHCLWcSpG3xt0TfckZ/Jm3xt/4wnbTxL/1fPo/aBaAR0JfFZByElFsvHH4Tw98j9xr+Tmf4mwEc68X/QY33bhKwjJPz0zNoN07Y79RLLSfwqduWxeGT5cy5x3zatkZBZHEeWp+6k1ekRv0/mbpJ6izcWfgobazR/27v5VFV//v93k7/nyK5cfCeJhw0ckDmXStyZ3RAmoTC8in3kiBORdFj8i8YIoiHgkLGLCE/ZSPQWJqCCmkzAX/SKVVl5rIRR2ap/5Eom0E1sCMsC30yoiSIvITOaJSCXaCuNyVpMKNkwTIwJNcCVgSWCFoAY1UAB9NCArBHKZ3FYHwo30dAYSbMFxYDWnIMUI3lT05cMHb0NgYlhvYA5BhIZTdkSGdulAaeLohgnk3TNOaDdpvTGYACozBpP7fmmncdp+N0q6RXyGRjjUwYeNIKjijC9mkcsgX113AHoG/GH80doyWnTHTEUpNwgLycdMSKLjQaYLVDqFair0oV0JBxrAlwz1P8b0I9MLY08iWfMw5dnUrL/0fGUhxcAEAuia254Gfrc7acX0dqtP8+85wJe7Q21vl/B0fS/3t50MOSYP8Pjrr9nf1/itRuk+HF6f/Y/wTv54TFC3B1pukVvU0HpNfpdcnw+IIMzwhYeDcS/3HH4CgFYGQJaHTsRgthfX90E59GYKyEFAWjDHw1brXblob/KvBoxKl9DsXSYBzQBAYR8Cyn1O45HQvKTdhggiAQNJ8S2yMtx2nDnyn4Z22dZYipndBJwNNE2jc+bSEUcGeFt6pGBhq5I3DrSAm4dF/FsKU+6nHCY0mCxq1ohJQasWIT+tdgnRr1Px9HH2cmYNP4v39w1Dnoov73D3v9Xfz/FGlN//8GER5EYdxJ4/vHAmvsf/+o2y37/z0YAQ539v8p0t1d+4V1dhujEUcLiAGAdlSFkXOsF+0PH6y7Oxvc1DEE46RVyAyME2DV0TJivRaxi5JuFqbEkZHkGwTqvHfDDBw9LPkWPMcEombyF0mTLPLI4UvxM5gNMxhfbknLbhEFC5xG/GkJTE8SiibczVsYZ2G4AB/SDXFQ8YWnjy041s9UwhblU2wB6eHgR3su+p+cAVJF2CIpBxihL13kMJgFKixI0St/NloIrpy+GWJZHDI4ONDPHet8jJMe1OWKfahJbgCethyDxDfh7YYhxjjQOOAJjQjkFbYbMRnLlxkdjHO+6syct6rI0vxNeB/yHM7fBB2D7zfv3ALHnCMSiHMp2SXrajxLH7dELk6CKB2T1t+5/XfeqsCSjW4uas0/SwJo9Cxqjg6EXC57V4mKLBW6Ixpu2MOiRtG9VbJMjsvfKmQCkhIIIl0P4P6jRVq/tbZXLTkbJrDlm2Ery0p0ccoYnLC2oGBA7u5UCL6aUEeisrospxhxsuSVas4xJEux4TgPHjEP6jvXuWY7AWvncTq0Va/ylwxCK2ypQ4HQGJw/3x4tJCAtZUOazMG/bWTrUCG/FWOrFNuN6MjJmnXckwbDaaYIdDJ1I4+W6THVsiwjNEHnXdjUbejxinomSetQD80OryOPAQiLIJ4YEKOBpTpbG94MYjj1EpqqqYmtaRqK2m+WWWajpONJXLRNVba0AIAGtqr2z1YyqRgUnOekdUNHU8au7TQEj46atkSb7YY2mxDlRXaDvdXAWuoHmJwVVrTWDSbrEzqmCQUZFAGZyHXtIPpdKMDWXXFJx03ms10bFXiMxnI1ayGLpzS5ZCF9ozlsryHNlDCu7ILreSyLthMvVfdYVl0qW+ViFfHSvbSFAC2BG20sB5sAWC8gJT2VvUAgOKHbaWi1+75e/ln3nYtYE/+ZFuHe60Fr13+ODqrx39HRbv3nSdL6oUr6HsUqERaxpSeUCNeqa10HkT8ghnNgzWjq+m7qDixCNnNTDC1CiZbVhJGu+ybSdotS0kXAZggRtKy053U3xAHnLwL0wYsgBwgSYzoE50dcNCVB21vi7/C5d7+Kd3d1Uj8OPG0fnZB5bgjQA84zMJd0LGmWvXouPooPm3VkfdCUPVU4FBvAaPatnLLZ+9S68zWkze2/lI77jAJr13/6lf0/PUi79Z8nSY9o/5Wl+PJNP0Tf42EwiSgQdfeVG5x1+i+NObreH8//q8//dzsHRzv9f4pU1f9i8F6m/8nI9Rw3S6csCf6Uy6LX3/GyJ1hAuYc5WOZAbKXv4TIlT7JQOnU2Aap+TFgW8wH5BecvfhWgE8pZlnhUflVhGG/tt6QDg7/oHMBxXWFOk5Es/EJ+qkJG1Jqhy40/MwENGkiB32AMOd0CeETTG5Zc424b2Q3NLUE+fOB0c8DNcHLTDAiTVsz8BoATmgI1YcDxnxvcANrcgsdY4geRKUPNjQrzvynmLdefga8CMEtL9wp+HXxrlqViB4CaOgM7OA4mmazGWxsQt9/KYhBx2ohNLpLcmahNEiDhLPObUFGiv1GrorEHj02b2/8RaBFK2fbDwDr73+kfVf2/g87O/3uSpOw/LmKtGANWz5Y9bIT4QcrVY/iNjzRCAFIqCNaavIImSwfK5qD3sKGOZyOc/VajlIQ+LHHeCMfXttE0kaz4tamn/VV7wP/ZaZ39NwfD+0YA6+L/w26v6v+/3O3/f5pU2f+vjQ16ul9wJJ8uYjzGELt/ZNQCFxDGl1NFSCHmQpwH5C/RbEnQJSYSl5T9LxQrBkeznNHsobaoIE3grPEVIFQJUqn9afp/jf4XAcoDjgOt1v9ut6vO/+T7P3udw6ODnf4/RTL1H8WgcNFO867/TA3BUgcOa0+DydR2524ApYIwSBe21Fwnj7cq4Vhb2gz0lmiSTwXipiowNRCE9eTEoNiVIBEURxtfGRhvgHN9K1PNhGjlU40YrMfkRhFLZWiqP4HxmlLvmmez8nBd6qVnYi8E+ZtzpcA7PwD/L/CIZqthlG89F6jxqdvrHwJkzVZNpDi5ow1azPzjAq1qUW39DEq/q5ZRy9jyQ1hi6QOZWmrKmCupdj6zfeAocfEQFPU3qwEsneORBFVo6+rZCGTrvrUTcOaDGQVeBFJmy/W1ADd2WDBzJ/QCVFQO9EaXVXMGW3RlrSPrkcd6w7EyWgHxz1I2w5xyPHTFrinIe5pkNG/byxJQ+xMY1fA0SyMdhfwOy8WbCVS7WMFcFuDswiCauzMNoVuByxJ8+FJkur0yZNFdA9LC1s2+BSsXMx6ATiygwqCWnboTgFrZyFvaQ9mqtoJCccFAYNXexxK8OM8s40ejeZlaza43x6/PhhfHJ2elXELmCPWfCZsNKhlEbs3OF6cb8tCYDXKD6eQjTo3dxny3QP+9sB64bfkG2F7pvALn89fHP569Pzu5env529v3Z5c/X55fNeI/IHIXLP+NaZht0ZDxQVjZGmYl9cEEriI3CbZJy1Yj2fdtmnrtijvbqpbNOLXNFbvvjb5r3JdYg6B3FGJpbvtBIhtWn5cWR559v52bsBQWHtcyEVdGwhHHuP4iOLCVazf1cqO904WFeXyGWna7vFbnebmiwFFNMi9suTwg0FSbtaoY1Xq38WMYzMHSc36RsBEtCzseQf6RplUNiIXgt6fUDdPpn9VMhtuxv+t8161kcPAaUKz/dXV1UcoKoiAN3PCUhu4CSGeRD2PTYadUJqZJIKymzO2auSBJfnAvCrDm4iMR0LfKIHmzYVIiV2kqt/wXTG1uXymKVQoSljKPQax5dXJRYpSe+l83IuQlV4wFcxZmM/oah8MabWLIlPbRVN4KnpIDQs/X1K9YnWY4plNZ7bpsJKGtAvQAU51bGFvUmotadm58K9iY1NUMd6UsiijeU1JyNgp8S9pc87si5tP8PEBezPz6IH+r1h6e1QVdMAZl/eVx20lZSJOq9298fFBrKYtZyCaLYYy8B58Il/SCkpCDgLq3w2t6A5bI6BJd8ycK3VU+OjBlPEVRMUrjpTfvIg4Y83GAp4YHZAgWxs9CehwtbtyFaaMx0qj3mRCmelRoEn/vQKZ7ULBEqnqDF1rW3Y2OIRToqetsqF/Gu9FGYZNywGtyxzZc/Fixyc8kQe+XLuBDCJsuToMq56kfZLMBeU1n4Pcujy8Ndi0xUU2UbbN9sTb70dgf6wza9sZM0vPajcuo32fKZgPDqcKH12C+BuSg12ni+Kee3tqlNWnN/K8hBR9v/1d9/b/b6e7mf58k7X3E6z/2rL3NLv+wbbt6LmeZcWxcrzrRdu/BM9VLzd7289f3Pa/ZMHhse25Tc6Bx0gFXvKoTOFVGYyBTzKfv7PnXm9bY/5j5fsCTTFz7Nsr8Cb3HQuC69f/+y9r+/8Pd/q+nSaY9jcUMbrECeMH807zzfxCd/6UtBeplEIgP30VqORAjOwwTP/5q3qfu3A3SGv3PZzch+BGDtxvyrQ3AOv1/eVjd/9M77O/u/32SVHG7fOZd00T6U//m+jaNbbYIFQIFsoNSs6HGy+X3spcjsZFR7e+ATe7YONWc0pxsExG7LYzNaY3+6+ntB90FvC7+A83f3f/1idIS5Ra9/qUN9g27Y4wtFEs3/owTNrOhVOjbuCtDrA2Rb3+5a+l1m9agdXVy0dpvYV5rcHfXtPjz4cOHX7/duM2cLbb2IVSbhhsCLbUq9w+Za9uAlQTa2qpl8OhtwcG8ZbtAxoXQHhEpDq0g4Np8v6bbre76gS5umN0/qO4iz90yafQbltMwQ9Yy1upstRa44fKb3GcpV+zKC15NC3LV5b+yd/ggV/DgM46cN7P/6gKbew4Da/d/H9TOf+I/O/v/BGmj63CqB3yqA4U+lbL9eLFiu9fTjhzLbJzmRM3U1YaaJUubdeO3wR62p5txW6P/89h9+DsQ6/y/l93q+w9Hvd3+76dJFf3H/pZ3ZvsVnW+h2HIPPIT8pHF73m0pQ/Ae13Ih84L5x6rcZ3sVxNrJIuk45FsNm7bI4/faNvn7rrVCRXmAWO2vFIDkF7m4ajg82EFmYacot8SQYY1ZEB3LzcGykPYOzQaNPU7wMShW/O0iK1/+/tuSza65EfEvmzY3Aag4K/1/Vl6sLxAdLHEmu52aQd2tT9w/rbH/yh/+qPF//6BTnf+D+P/lzv4/RSoZtxUXJxSrAq/VdQk/S9E4Ke2h+WwOcTc4aEtDYvksGAxx6Hu1ioY32TpVvQ1JXlxqe66N0wpbbYISV5fma76GUVNKqM6Db3jsu7Kubdw0UiFfkhEGkCX7Uhts5QEX9vve69e68vqBXMXnci+mgC5u56D2vGuQUBTcZj7Ac3/IIj9UBOX3wMhxiMX5ZkXyS+vk8uz46gxvOHl3cYq/fs2bLF81gje7lPL0K0uYC+5RkVe658O89+XXvLtLw7a2vEzcBVDdNVr+ujIAOWyQqJUt5j1VbbSWca92eeDTs/FYXHBA3rCIvo1Ok8VlJjfg5Tboks4DepOzM+8o5XwlNIjmTL43pY+lnI/fUOqLFQf7frs/zBt4vlQ1MWj42HpC6opCmjWlfAlSXVcIKgtp1hbSeDHSTmE+B4XBC6C+VEUB3D8nBbmvcph3cDVJ+ZIt6ZrV+tE+0/83LtbXTPp6hf9Te+CfNjXGf3PZxY/1AOzq+K/b6/eq7z8fwtdd/PcUaY+cqlPAstPFIwxNZtiy5GFjMXukDxcPCM2ciSciHz0K2OocSf6h3ficLNhc40QxKCNLL8CwSe9+j+hHhORDqqJpgqeWb6aM0/zkcumJ2eIBUUdM4k2Md0St2sF28suv4rVb3RAUblnVN5LER6u8FDAQ+A1j6uFOZo7nhgCHhLi15x6KZ21lzIiWVP7KT4/tEfPmhJSBRfP1660VcJWQFm+mxfpXG7054Yiy52Px8Cu4UWLXtopkkYmAzT5QIADB//Vbib58x1UA1rzJL6jIQ3zkkRHHLmdQ6cWVKnPEO1HlaBpRiaVQwAhsPgYhmvgZnykfu+AW7ou8JjlT0Pk+SZB1gA5SLidNpfCogcxEjjtGT4kGGlm99AGZbbidv3YBGUqsaS4COc/F0Nuy66+7cPGok1U6nwS9Udwrt6I3zHc1NpLVGgPqL3N8TEGzrPJNI0IHrPrtDeL7HhlzdXcfviqLWtxUyHNjeUGMmPDeA1/BT1gsf9nk+NUr+KXPfF7CEIAHJfgCqJ4pvkB2Fh1zcE0wu/zxHceTDl3VfO79yl0P6r7Ac9yAIN3PbqfX7zSouVU6KCzepVMujhdngryZ+J+cS4cP/cPXgbDTf4BFL5XtVsseHkBRax6LGTu18lPIvDEdvw7GujWMFq4LgaEonXZF6sxzomiU8yOqgnQl8Qiv4txKAwiCUXYyRS0YP85PT8gx2AJypocwUp6q3NM9YN/gY3X5SCdO0Vm1+8AUyIuEzaF4UgaGF+Uk8t03Nwz1HWBNNgvYqR8Z9Fx8/5vo0xnQvKiP7aMqUwUGKceLJ3vQ9K1irEJm6EG0Id1k/AVMhr+jwCd05gbqLghVVAZk5Py0gqoEjTtibtE6lDHex8JQSDyLyyEkyA2T+dp3+Uo0BQFtMUIVzDJCwnNfjBd1zJQB/VTY7RFQVk4ufjo50xhh27jlWQHC88HaqhkESX+iShTQEIiXhN9dvvqENA3xjUuBkM7g+fPHN0Hoe+CicaJftn/hQADsM5CdSK3rtSWybQ9wGrnetQqmJG3vkrBKtm6FQF7BVvXaJYzk+P4g0APBYxja1xG7idpSYu0ySX4AAg16sRChu6XjVfnCgNku5+F5JCw7HV4H6P8F40Vhv/AuCJn7FqpjCQlClFPcLErjZrtLILOkaPhR6nr+tCN+svFCWHR1bxdIkRrhhvLmVvAUKecyJiX60lgc3oIIQmv8oU2zauSYyEsKoSPd4qHQmZugNEh3wFXy5s18R+Gj+y2+njgT5vh03laLNbKoPWHtlLGQt/OqbTcO2vPunoQgWi8IHKaJ0aHHxstson2loWoxGLHFqkoY88fb8EVV+/KHY2EqgTkNLOGFZRNeBe71A4Gn864jtekyb1iTOAH/Jxs5wL12sSVSEDMK2agNbn7vOwfkFKAAeeIuNw482XuFJ0lzMnPoOEqgmyIWfoTnaXRz4XQqBNGbCaTXJBwfjEBEISHs8t3cqkxkXLmXklScR/mW11z6nNXgNXD0gk6OyUjMLaFWx3SGbJ2BSAjRg16YCwHPHX3AKBDHMtIFooY6mCvLybGapTK7VPWhcCc91/HADlzTRbHAL1GuIvOkHSVxX9FVJnG1zjrNhLQ2oDNK3Mj7s13pqLZ41oa3e/3/lu8fCUEGy0RoUO7x9EbEIy6oZQRuDV6txcTJKEsO7D6+G+z7AX5yQ7WMqa13IQW5V4u6r9Y6dSxXheGWY8MVgCou44NgST9fjgPNjg0UKoYJcMuNO0+hsoSqbtdQ88pagoq84mouJVi4dAyC9cq8WmOFiQORmrneFIV2gdn4gYsd0mjfSlBWTUfmOKnnTJ8OoYY7RCTnwf11NavBhYaRgbozESLsEyas8ZTqAURIZOGn4FALLoMecqjvCLjGTuj17ai90eQZkrov6H2ua709fTuQ7krV+wXh0I4FCh0OZbkV4fngkLcCCjnLIjUCmzjqndnlzlGvV0CAgmfRYhYodVff9XyvDlj3ivHfAIKumPRB9sWQzcTb4JF4clIqRCHU+2ho0Nmr2vG7OxSkDx9s+UM9p6aawltlLkQLudE12sfcnBOaImjGD8ZgRQnuFxBZd3cFnA8fyD/gQ4FYqa1BtQkN1VT2aoulOTizX3X/RZMgunVU8cq5c3QCaeTbxQ76Fl6/NWyhi6emLwR3QTYhlgz4VGqM5rD0J9UYiXP74IEqNOqTWwq5V0N12kyQAmzCaIGD5NJkpl4PUYXTkBfjRg7gbaxMoOpC4SiXrzzNy56neTym+l3PcYgg8e6uVM+8GdKMFj/1pO4u7dIu7dIu7dIu7dIu7dIu7VJD+n81djdtAKAAAA==
  values:
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller
      tag: v0.0.1-dev
    imagePullSecrets:
      - name: gardener-images
    webhook:
      namespaceSelector:
        matchExpressions:
          - {key: "gardener.cloud/role", operator: "In", values: ["shoot","project"]}
          - {key: "shoot.gardener.cloud/no-cleanup", operator: "NotIn", values: ["true"]}
          - {key: "gardener.cloud/purpose", operator: "NotIn", values: ["kube-system"]}
          - {key: "kubernetes.io/metadata.name", operator: "NotIn", values: ["kube-system"]}
    vpa:
      enabled: true
    configuration:
      domainName: "... cluster domain ..." #cluster domain
      oauth2Proxy:
        sslInsecureSkipVerify: true
        insecureOidcSkipIssuerVerification: false
        oidcIssuerUrl: "... OIDC issuer URL ..."
        clientId: "... OIDC client ID ..."
        scope: "openid email groups"
      kubeRbacProxy:
        oidcCABundle: |
          -----BEGIN CERTIFICATE-----
          ...
          -----END CERTIFICATE-----
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden-plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
