---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+09a3PbtrL9rF+BK/dMkh6TsmTJ7tVMP6i2T49Pk9hjOem90+lkKBKSWFMES5ByVDf3t99dPEjwoZftOI+K00llElgsFvsEFgDzPddyoohbLguTmAUBjVvfPO5zAM9xryf+D0/5/+J3u9vrtY+77V6n881B+/AI/kd6j4xH7ZPyxIkJ+SZmLFlVbt33L/RhdeNvT2kw8ychi+ljtIEDfNTtLh3/XrdXGv/e8dHBN+TgMRpf9/zNx3+PXDpJQuOQk4QROebkdkpDMkr9wPPDCYkc98aZUG439sj11OeEp1HE4gR+AJ8EZBKwEZk5iTuF0vskpoGT+HMK9ZKp8d4JPQAQ0gl8ZSF5HsV07L+nHrn1odx/vbDJRRgsCAtFTUSJRDQmgR9Su2GfDt8NE8ANQJyw2QwAvD0ZEs+PecOe+ElL/CvRb9ijP+OW+Fe/mE5a+I/+k8/DVg5oBP1LIzL2A8ob39n8NoJ/R84N/JvM8DcDOI3v/g9qvHVin6WcnJ+eQbtRzH6nbtKwfY86LVkcXjXsOXeZR1uNkR82OA8an3qQVzy18n8ydeLEXjiz4FHaWCP/7c7hcVn+e73OTv6f4nEi/y2NOUhkn8zbjdCZ0T6pY4qGR7kb+1Eiig7Iv8FEEBcZhYxZTH5ORyCxNAER0moC/kumVJWZy0Zs+Un9RcJ0BtVAj7A08MiIEj90YzqjYQJ6gTrulCT+jJIFS0GR3AhYIWgiaAGUVQ4cVAvxQR8ldBaB8qF8HwEFqVBfWAz6kmGAYix/cuKAsqPvIxBiaA9AjqGr7JYM6cwJE9/VBRHM82mSRLzfanE6A1CgFCatF425pt2BfWC3y10vdZONNTKB70otOKII26NRwBbUW0MdgL4ZfTR1jJbsYqdDlpgdB8jLu45Y0YVGA7R2ANUK/Sv3CvqQcqwJcM8T/DOmLihbGnqSzimHoU6k5v8jZQkaFwCQcWJzLujZ/Jw159fx1Op/j7n2hD1aG+v8v+6x9P8Oux0sCfq/e9zu7fT/UzytFhlenv6P9S/wfk5YtABXZ5pc0/dJn3QOOm0yHFyS4RkBDe+E4g9nDI6SD0qWgERHTrgQ2vcnJ/ZoCMpKcJE/SsFX441Wq6Hhv/RdGnJqnUOxxB/7NAYjAp7llFod+6AB5SasP0EQCJpPieWSpm234L8p+Gct/clgUyumE58nsdRvfNpEKODOCm9VWQYaOiNw60gBuHRfhdlSL7WdcFkco3LLGyGFRhqRCf1r0E618p/Z0ceZCdg0/j9ut0H8e+j/HbWPdvH/Uzxrxv8dRHgQhXE7ie4fC6zR/zjuRf+/AxbgaKf/n+K5u2t91zh7H6ESRw2IAYB2VIWSsxvftT58aNzdWeCmjiEYJ82cZ8BOgFZHzYj1msTKSzppkBBbRpKvEaj91glScPSw5AV4jjFEzeQvksRp6JKjQ/HTnw1TsC/vSdNqEgULnEb82RCYnsQUVbiTtTBOg2ABPqQToFHxhKePLdiNX6iELcon2AL2h4Mf7Trof3IGSOVhi+w5wAg86SIH/sxXYUGCXvnz0UJQ5fT1EMuiyeDgQL+wG+djnPSgDlfkQ0lyfPC0pQ0S74S3GwQY40DjgCc0IpBX2G5EZCxfJLQ/zuiqP2a0VUWWft+E9gHP4Hwr+tH/YfPBzXHMKCKB2FeSXLKuxrPwckvkotgPkzFp/oNb/+DNEizZ6OasVv+zwIDGyKLk6EDI4XJ0FavIUoEzosGGIyxq5MNb7pZJcflbhUzQpRiCSMcFuP9skua75vaiJWfDBLZ8M2xlWYkuThmDE9YSPeiTuzsVgq/uqC1RWV2WU4w4WfxSNWcbnKXIMMiCR/wG9e2bTLJtn7WyOB3aqlb5SwahJbJUoUBoDM6fZ40WEpDmsiGN5+Df1pJ1qJDfirDlHlu16MjJmnXUkwrDru8RyGTihC4t9scUyyKP0Bidd6FTt+mPm9czu7QO9cAc8CryGICwEOKJPjEaWCqzFfNmdIZTN6aJmprYuk9DUfv1Ms1slLRdiYvWqUqX5gBQwZbF/vlKIuVGwX5Bmrd0NGXsxkoC8OioqUu02q5psw5Rnn+u0bcaWFP9AJWzQotWhsEkfUzHNKbAgyIgE18dyw9/FwKw9VBc0XGd+mxVrAKPUFmuJi184gmNr1hAX2sKW2u6ZnIYV3rBcV2Whtuxl6o7kFWX8laxWIm99ChtwUBL4IYb88EmANYzSEFO5SgQCE7odhJaHr6vl36N+85FrIn/TI1w7/Wgtes/x91y/Hd8vFv/eZJnvamSvke+SoRFLOkJxcK1ajdu/NDrE8M5aMxo4nhO4vQbhGzmphhShBwtqwklXfVNpO4WpaSLgM0QIvqyUp9X3RAbnL8Q0AcvgnQRJMZ0CM4LuWhKgra2xN/mc/d+Fe/uql39OPC0frQD5joBQPc5T0Fd0rHssxzVc/FSvNhsIKtGU45U7lBsAKPet7KLau9Ty87X8Gyu/yV33McKrF3/6ZXyfzrw7NZ/nuR5RP2vNMWXr/oh+h4P/UlIoVN3X7nCWSf/Upmj6/3x/L/q/H/7oHu8k/+neMrynxvvZfIfjxzXdtJkymL/T7ksevM9L3qCOZR7qINlDsRW8h4sE/I4DaRTZxHo1U8xSyPeJ7/i/MVvAnRMOUtjl8q3Kgzjzf2mdGDwF50DOK4rzGk8koW/k6/KkBG1eugy8WcmoEEDCdAblCGnWwAPaXLL4hvMtpHDUN8SfIcXnG4OuB5OppoBYdKMmFcDcEIT6E3gc/zfLSaA1rfgMhZ7fmjyUH2jQv1vinnT8WbgqwDMwtK9gl8F35ylicgAUFNnoAfH/iSV1Xhzg87tN9MIWJzWYpOxJLcnKkkCOJylXh0qivU3alU09mDbtLn+H4EUIZdtbwbW6f+D3nHZ/+se7Py/J3mU/sdFrBU2YPVs2cMsxI+Srx7Db3wkCwFIqSBYS/KKPjV0oGwavYeZOp6OcPZbWSkJfVigvBGOr22jbiJZ0WtTT/ur9oD/3s86/W8aw/tGAOvi/6N2p+z/H+7y/5/mKeX/a2WDnu4XHMkniwi3MUTOHyltgAsI9uVUdSRnc8HOffKXaLbA6BITiUvC/heK5cbRLGc0e6Q1KnATOGt8BQhVgpRqf5rxXyP/eYDygO1Aq+W/3TmS+d9HB912+7DdxfWfo+Pd/r8neUz5RzbIXbTTbOg/U0Ww1IHD2lN/MrWcueNDKT/wk4UlJdfO4q1SONaSOgO9JRpnU4GYVAWqBoKwjpwYFFkJEkGxtfGlgfEGOFdTmSoqRAufasQgPT5OGLJEhqb6FSivKXVveDormuvCKD0XuRDkW/tagbd/BPpf4hbNZo2Vb74QqPGp0+kdAWRNVt1JsXNHK7SIeYMcrXJRrf2Mnn5fLqOWseWLoEDSBxK10JQxV1IefGZ5QFHi4CYo6m1WA0g6xy0JqtDW1dMR8NZ9a8fgzPszCrTwJc8W62sGrh0wf+ZM6CWIqDT0xpCVv/S3GMrKQFYjj/WKY2W0AuyfJmyGX4rx0DW7ocDvSZzSrG03jUHsT8Cq4W6W2n7k/DssFq/voMpiBXWZg7NyhWhmZxpMtwKXJfjwpci0O0XIYrj6pImtm2MLWi5i3AeZWECFfuVz4kwAaimRt5BD2Sy3gkxxyYBhVe5jAV6UfSziR8N5sbeaXK8Hr86Gl4OTs8JXQuYI9V8xm/VLH4hMzc4Wp2u+oTLrZwrTzixOhdzGfLdA/63QHpi2fAtkLw1ejvP5q8FPZ2/PTq4vrt5dvD27+uXq/LoW/z6RWbD8HdMwW6Ih44XQshXMCuJTi7BWBMuQ/GlwdXr2+t3g5ORsOHx3ffHz2et6FJutuRO3QIu01Lx2q6Rj5J+tXEgdF6wmtxKUtWYdjjiJ9Hzq8J/pooIvMDX1Xqz+bIt8+g3K2Go2G8r6nNNkg6K2x2Yguy/W0G14dnb67vTi1eD89Tvk0SW0MwRgbZMlYVo50JXXECpwk+Et0rSUJ/NDiyZuqxTONMtlU04tc8X2BwP12rzUCgSdUYqlueX5sWxYvV5aHMn6w3Zu4lJYuF3PRFwZCVts4/uLoGNTrF0n5bX2ThcW5vE5atn3y2sdlLhH4KgWGRaWFCOBpkrWK2NUGd3al4E/B37i/DJmI1pUdrgF/SealDVgJBRfa0qdIJn+Wf7IMB3/+4Pv26UPHLxG5Px/X19fFj75oZ/4TnBKA2cBXWehB77J0UGhTERjX1hN+bVtfgVO8vx79QBrLj5SB3qNIkheb5gUy5Wayiz/JVObG1ayYrkHMUuYy4I+uT65LBBKL/2s8wiykit8gTkL0hl9he5QpW/CZZL20RTeEp6SAkLO19QvaZ16OGZQUR66dCShrQL0AFOdaRhL1JqLWlZmfEvYmL2rGO5SWWRRPKem4Gzm+D7cgNfb2xUYP8SMr8a/EjeEzKPZfpasmPn2QfFCpT3caw6ybDiV+s3jtpOwgMbl6NV4+aDWEhaxgE0Wwwh5B3x6XJL2C0IKAua8H97QW9CkxpDomuAM9Ulx68uU8QT5xSiNhza9CTlgzMc+7nrvkyFoSC8N6CBc3DoL08ZgpFwdM8Fa1VkNs/P3DsTb3ZwkUlXVRFFF3bPRNpocPXUcE/WKeNfqWGxSCkxdOLHh4t2KJFWzCzrfP4dPZ1GyOPXLlKeen8765BWdQdy2fH7EINcSFVvXs23Sbyuzd7XjsU4hb6+MZX9eOVER9ftMOW6g+FX4+wrUV590OwerKL6BEt9Yga8bnTUADOweYf53zfy/QcWPl/9Xzf9oH7S7u/n/p3j2PuLxL3uNvc0Of7Esq7wva5lyqV2vPNF648ErFUvVxvbrF/fdr1ujfLfdt6spUDvphCue5Qm8MqExkMnXUx5X4+yez+lZo/8j5nk+j1Nx7N8o9Sb0HgvB6/I/eoeV/R9Hu/y/p3lMfRqJGfx8BfiSeafZ4P8oBv9LWwrWy2AQX70J1XIwRkYYZn381dxPPbgbPGvkP5vdBPdUGG8n4FsrgHXyf3hUzv/qHPV2+R9P8pTcLo+5NzSW/tR/uD5NZZsUsZyhgHeQazaUeJl+UfRyJDYyKvwdsMkcG7v8pTAnW9eJXQpr/bNG/nFRS61sfMT4r3Moz//rdLvHh8di/397t//rSZ4VExv3lfvSrMUnSgFFQEtzvaI0jhgHjASSoKn+gM7jcTMra7mBw3mfyLeNmlwstRikjntZnmqmZu+A9djMqj1sextoinTk2V1OrArqGehmv4krF80Pz5TKvZBZsjsF+bd81up/ubz5oLsA1ul/8Px2539+omeJkhej/qUFezUa2UihXKo/xzFoYSgVeBZmZYrcAPLs17umXrcHlXl9ctncb+K3Zv/urm7x/8OHD78927jNjCyWjiFVm0YYCi01S+cPmrltgJUE2tyq5Yh5lqBg1rKVI+MEPuY6P8s3rSLgynqp7rdTzvqFIa5ZHe2Wd5FlYbm0QDXpFPhB1jJyNSyVC7Jh+oXcZyEzNooJD3UJGeX0j+LswIOmArqf8czpZvpf+yD3MwNr9391K+c/4P92+v8Jno2Owytv8C0bCr0rdXt7sSLd+2ktxzIdpylRUXUVU7MkNaSq/DbIYX+6FZc18j+PnIffA7XO/ztsl+9/OsYjAXfy/wRPSf5xvOWdGV5J5pvIttwFDyE7aaQ1bzeVIniLETl8vGTeQJX7bI+CWrtYIB2HbKtB3RY5fF/ZJnffXBWoKA8QUfsrBCD5RianGA4PDpBZ2M7LLVFkWGPmhwO5OUgW0t6h2aCR4wov/Txjyso/ZelD3y7Z7JIpEe+qLrkVQEVp4e9ZMdkpR7S/xJlsH1QU6m59+v7PGv2v/OGPGv/3ugfl9R+I/w93+v8pnoJyW3FwUr4q/Eodl/SLZI2TQg7iZ3OIS42DtjQklteCgokTE6N5w5uknpZPQ5QHl1uuY+G0wlZJpOLo8iznx1BqSgjVeTAbHvtSymsyThordV92I/DhkxxLrbCVB5zr73vnL+nK6w25is9lZruALk7nota8bXQhL7jNfIDr/JiGXqA6lJ0DJ+0Qi7Jkb/Jr8+TqbHB9hiecvbk8xV+/ZU0WjxrDk90K3/Qti/gV3KP8W+GcL/Pct9+y4S6Yba15mTgLqJx1X3y7MgA5quGolS1mI1VutPLhXu1y36Nn47E44Ii8ZiG9CE/jxVUqM1wzHXRF5z69zciZDZRyvmLqh3Mm75vU21LPx68p9cSKs3W/7D/zBL4vVUyMPnxsOSFVQSH1klI8BLEqKwSFhdRLC6k9GHEnMJ+DwOABkF+qoADun5OA3Fc4zDM467h8yZYeTWp9aa/p/xsX62gifb3M/6k98E/71MZ/cznEj3UB/Or4r93pdUr5v+0jeLuL/57i2SOn6hQQOejiEqY6NdxoyMNGxOyRPlykT2hqT1wR+WgrYKl9eNmL1pIMl8g4UQSEkSWXoNikd79H9CWC8iJ10TTBU0tup4zT7OSSwhXz+QXitpjEmxj3iDcqB9uQX38Tt93rhqBws1G+I1G8bBSXAvoCv2FEXdzJwnHfJeAQE6dy3VN+rb2MGVGTyl/Z7uE9Yp6clDDQaJ6+vb0ErhTS4sn0WP96ozunbFH2fCwufscTM3DXjopkkYiAzT70QACCv/VdyZ68x10A1rTJDqjKQnykkRHHLidQ4ca1MnHEPZHFaBpRiSRTgAU2L4MSTfwypSEZO+AW7otvdXymoPN9EiPpAB3suZw0lcyjDJmJHLeNkRIN1JJ66QVy21A7u+0KPii2phkLZDQXprdpVW934+JSx0ZhByGMRn6u7IrRMO/V2ohXKwSo3sz1MRmt0SieNCZkoFE9vUm83yNjrs7uxVvlUYrrCrlOJA+IExPee+AreDGL5C+LDF6+hF96z/8VmADcKMcX0OuZogt8TsMBB9cEPxdfvuG4062tms+8X5n1oM4LPscEBOl+tg86vYMaMW8UDooQ99IqF8eNUtG9mfhLzqXDi97RK1/oaZHWaJZtl8sedaFoYx6JGTu18pPzvDEdvw7GujWMJq4LgaIonBaAvTP32aNSzrb4i64rjkd4JedWKkBgjKKTKWqB/Tg/PSED0AXkTJswUpyq3NMjYN3iZbWZpRO7kBuV80AVyMuYzaF4XASGB+XF8t5XJwj0GaB1OgvIqS8Zdp0Q5U3vzoPmRX1sH0WZKjDYczx4ugNNv1eEVcgMXYg2pJuMv4DI8G/oe4TOHF+dBaSKyoCMnJ+WUJWgMSPmPWqHIsb7WBgKuSwGFoSQIFNMRuBQ3IWuIaAuRqiCWEZIeO4Je1HFTCnQT4XdHgFh5eTy55MzjRG2jVteFCA8X0FrNaND0p8odwr64MfAkOTN1ctP2Kch3nEtENIfOFiMSAS1t37gueCicXEoD++3Wt/ZEADLQ6vUul5LIttyAaeR496oYEr27U0clLutWyHwLSeruu0aLDnePwz9geAxCKybkN2GLcmxVrFLng8MDXKxEKF7Q8er8oYhs13Og/NQaHY6vPHR//PHi1x/4VlA8usFVMcSEoQop6iZl8ZkuyvoZkHQ8KWU9exqZ3xl4YHw6Oq+X2CPlIUbypPbByIDXsakRB8aj+bNDyG0xh9aNatGBkQeUgwD6eQXhc+cGLlBugOO4jd35tkKHz1u0c3EnjDbo/OWWqyRRa0JayWMBbyVVW05kd+at/ckBNF63sFhEhsDOjBuZhXtKwlVi8GILVZVzJhd3oo3qltXPw6EqgTi1JCE55pNeBWY6wcMT+dtW0rTVdaw7uIE/J90ZAP1WnlKpOjMKGCjFrj5ne9t4FOAAt0TZ7lyoMneSzxJIOtmBh2tBLopYuFHeJ7GMOdOp0IQvRlfek3C8cEIRBQSzO6Jbpd5IuXKvZRdxXmUZ7zi0mekBq+Boxd0MiAjMbeEUh3RGZJ1BiwhWA9GYS4YPHP0ASNfbMtLFogaymAmLCcDNUtlDqkaQ+FOuo7tgh64oYt8gV+iXEbmSQdK4r5iqMzOVQbrNBXcWoPOKHZC989WaaBa4lo73ur0/lvefygYGTQToX5xxJNbEY84IJYhuDV4tCYTO2Mb0rB7oEkhevPxlROoZUytvXMuyLxalH29dUPFcmUYTjE2XAGo5DI+CJb089XhhbWODRTKzQS45caZ51BZQlWnE6l5Zc1B+bf8aE7FWLh0DIz10jyaaIWKA5aaOe4UmXaBn/EFFxnSqN8KUFZNR2Y4qevMnw6hmjOYJOXB/XU0qcGFBstAnZkIEfYJE9p4SrUBERyZ+yloasFl0CaHeraAa2RCr29H5UaT59jVfdHfF7rWxelFX7orZe8XmEM7Fsh0aMoyLcIz45C1AgI5S0NlgU0cdWZ2cXDUiZoQoOBe5Ij5StzVez3fqwPWvdz+G0DQFZM+yL4w2UBLKB2KK6elQORMvY+KBp29sh6/u0NG+vDBkj/UdaqqKTyV61K0kCldo338mlFC9wia8fwxaFGC+QLi091dDufDB/JPeJEjVmirX25CQzWFvdxiaZdZPq56/MKJH77PDjEt7kBAJ5CGnpVn0Dfx+MVhE108NX0hqAu8CbGkz6dSYjSFpT+pbCTO7YMHqtCoTm4p5F4O1a5D0RUgE0YLHDiXxjN1e5gqnAQ8txsZgItIqUA1hMJRLh55npU9T7J4TI27nuMQQeLdXaGeeTK0GS1+6knd3bN7ds/u2eD5f7LmGWwAoAAA
  values:
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller
      tag: v0.1.1-dev
    imagePullSecrets:
      - name: gardener-images
    webhook:
      namespaceSelector:
        matchExpressions:
          - {key: "gardener.cloud/role", operator: "In", values: ["shoot","project"]}
          - {key: "shoot.gardener.cloud/no-cleanup", operator: "NotIn", values: ["true"]}
          - {key: "gardener.cloud/purpose", operator: "NotIn", values: ["kube-system"]}
          - {key: "kubernetes.io/metadata.name", operator: "NotIn", values: ["kube-system"]}
    vpa:
      enabled: true
    configuration:
      domainName: "... cluster domain ..." #cluster domain
      oauth2Proxy:
        sslInsecureSkipVerify: true
        insecureOidcSkipIssuerVerification: false
        oidcIssuerUrl: "... OIDC issuer URL ..."
        clientId: "... OIDC client ID ..."
        scope: "openid email groups"
      kubeRbacProxy:
        oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== # base64 encoded OIDC CA bundle
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden-plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
