{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oidc-apps-extension.clusterRoleName" . }}
  labels:
    {{- include "oidc-apps-extension.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "services","secrets","events" ]
    verbs: [ "*" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments","statefulsets", "replicasets" ]
    verbs: [ "*" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces", "pods" ]
    verbs: [ "get","list","watch" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "*" ]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: [ "get","list","watch","update" ]
  - apiGroups: ["extensions.gardener.cloud"]
    resources: ["clusters"]
    verbs: [ "get","list","watch" ]
  {{- end }}