{{- if .Values.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: oidc-apps-regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson }}
{{- end }}