{{- if .Values.vpa.enabled}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "oidc-apps-extension.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oidc-apps-extension.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "oidc-apps-extension.fullname" . }}
  {{- with .Values.vpa.updatePolicy }}
  updatePolicy: {{ toYaml . | nindent 4 }}
  {{- end }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ $.Chart.Name }}
        controlledResources:
          - cpu
          - memory
        {{- with .Values.vpa.minAllowed }}
        minAllowed: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.vpa.maxAllowed }}
        maxAllowed: {{ toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
