---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1dW3PbRrLOM3/FHGi3YmcN8E7ZrMqDImkTndiWSpSd3dra8oLAkEQEAggGoMQoPr/9dM8FGFx4k2xZ8XIq5VDATE93T8833XND6LmOaUcRM50wSOLQ92nc/ObTphakw36f/x9S+f/8d7vXP+z0B90O5mt34cc3pP+J+ahNKUvsmJBv4jBM1uXb9P5PmsK69rdm1J970yCM6aeoAxt40OutbP9+r4/tP2j1O90ePm/3D/vtb0jrU1S+Kf2Xt/8BubCThMYBI0lIRJuTmxkNyDj1fNcLpiSynWt7SpnVOCBXM48RlkZRGCfwA+zEJ1M/HJO5nTgzyP2CxNS3E29BoVwy057bgQsEAjqFt2FAnkUxnXi31CU3HuT7n+cWOQ/8JQkDXhJZIhGNie8F1GpYJ6MPowR4AxLH4XwOBN4fj4jrxaxhTb2kyf8V7Des8e9xk/+rHsymTfxH/ckWQTMnNAb50ohMPJ+yxncWu4ng37F9Df8mc/wdAp3Gd/8HJd7bsRemjJydnEK9URz+Sp2kYXkutZsiOzxqWAvmhC5tNsZe0GDMb3zpRl6Tavv/8cyOE2tpz/1PUseG/t/udA/L/b/f6+77/2MkO/Le05hBjxySRbsR2HM6JHVG0XApc2IvSnjWI/ITDBHEQUMhkzAmP6dj6LE0gS6kYAL+S2ZU5lmISizxSv5FgnQOxQBHwtR3yZgSL3BiOqdBArhAbWdGEm9OyTJMAUiuOa0AkAhqALDKiQO0EA/wKKHzCMCHshdIyE85fGE2kCXjALux+MmIDWBHbyPoxFAfkJyAqOENGdG5HSSeozIimWezJInYsNlkdA6kABSmzeeNhdJdy2pZ7bLoJTHDiWLG9xyBgmOKtF0a+eGSuhu0A9S304/SjlaTVRQ6CBNdcKC8WnTkii4VG4DaPhQryFeWCmRIGZYEumcJ/hlTB8CWBq7Qc8qgqROB/L+lYYKDCxDILNFYcH0aTxk5v45Ui/9u6FjT8JPVscn/6x2W/b/eYbu/x//HSM0mGV2c/MP8O3g/x2G0BFdnllzR22RIOq1Om4yOLsjolADC2wH/w56Ao+QByBLo0ZEdLDn6/mjHLg0ArLgVeeMUfDXWaDYbiv5rz6EBo+YZZEu8iUdjGETAs5xRs2O1GpBvGg6nSAJJsxkxHWJYVhP+m4F/1lSvNDM1Yzr1WBILfGMzA6mAO8u9VTky0MAeg1tHCsSF+8qHLflQjRNOGMcIbnklpFBJI9Kpfw3oVNv/s3H008wEbB3/t/qD7qCH/t+gM9jH/4+RNrT/B4jwIApjVhLdPxbYgP+H7ZbA//6gPeh2O9+0OmABnT3+P0Y6WAf/vYfB/0HjYCvwN02zcXfX/K5xehshNURiDESUw8zB1mp81/z4EfKZ4C5PvIASI7ddYBgqQITGcgYx85x26ifEEhHtWyRqvbf9FBxOzHkOHmwM0Tv5gyRxGjhk0OU/vfkoBUFviWEaRNIC5xV/Ck6PY4o6sLMaJqnvL8GXtX2Uz+URB9ZgNX6hgjbPn2ANKA8Df96x0Q9mITCVh09CcqDhu8JV9725J8OTBKODZ+Ml18rJ2xHmxaGLgSP/3GqcTXDyhdpMqg8bw/bA4xdjIX/GvW7fx1gLKgc+oRLOvOR2KyVj/qKivUmmV/Uy063MsvL9Nrr3WUbnL1yO4ffbN27OY6YRQcS6FOoSZRWfhYc7MhfFXpBMiPFXZv6VGSVaotLtTa3+Z8EAtZbFnqMCMpuJ1pWmInL59pj6W7YwL5E3b1ksXePitwzdQKQYglnbAbp/M4jxwdi9a4lZOc4t245bkVewi1PX4Aw2uQRDcncnpwLWC2oJVtbnZRQj3zB+LauzNMuSajjKglh8B+Wt66xnW17YzOYLoK5qkT9EMFxSS5UKhOjghLrmeCkIKSsb0XgBUFur1pFkfifFliU2a9kRk0abtCcAw6qXCPpkYgcOLcqjd8uijdAYxxGOqbvI4+TldJE2se7rDV5lHkfCMIChbUi0Clb22crwpgnDqBPTRE6R7CzTiJd+uwqZtZyWI3hRmCqxNCeAAFvu9s/WKikfFKznxLih41kYXpuJD54l1bFEwXZNnXWMsvx1Dd4qYob8AZCzBkUrzaCrPqYTGlOwQR4Y8re26QW/8g6wc1Nc0kkdfDYrowKLECzXqxZesYTGl6FP3yoNmxtE0y2MSVywHSdMg93MS5Y9EkVX2lYxW8m8VCvtYEAr6AZb28E2BDYbSKGfilYgECTR3Xpoufm+cv1d0iTFBUUbVOYBLJ5xR4RRcEiw+JY+Jk2c2bEs/8NyBKXz8IH3cUI4dIk6FGZNAT0V61MZlVhYtWUHQZjwaRym1WhlNWr5HT9M3aYgbAqVlus7O8HaDO1FjFPvOYTxXEy8FhmgtelvRGhQ51pmKZP/nliZ+sxCnjEYx3X2TFN/zR8x/S31YtD8Mw5CxJhAM0I7hCSrCOEONTQkxgrVcZafa7yVwOdLB7H7dO+0Yf5HH4nvvR68af233+rl8z+dHs7/HB729vM/j5GezvzPJldVxB75ajVmMUUkFPPQqt249gJAMS04aMxpYrt2Yg8BDrcLU7RRVKBooJy0amwifDeeS4QIwxzs1/pz1TDEguAvAPZBQaSHJHFOB8m5AeNVCdLmjvxbbOHcr+DdXVXUz0NP+UeWHzq2D9Q9xlJwl+hEyCxa9Yw/5A+2a8iq0yxaKg8otqBRH1tZRbfnS/fhh6Tt8V+0yn1GgU3rv4OBNv+P+TqdTq+1x//HSF8h/kuk+PNDP6P+ZORNA3TN7z4T4Gzq/wJEMeT9bP5fp9sS+/8GkKl7iOt/bci/7/+PkZ5q/88H71X9Px7bjmWnySyMvd/F9ozrl6zoCeZU7gEHqxyInfq7v6qTx6kvnDqTgFQ/xmEasSH5F04p/JuTjikL09ih4qmchmHGC0M4MPiLLnCOQRVY0HgsMn8nHpUpI2v11MUGxDmnBhUkoG8AQ8ZrIQau6ABi8T+3rSugyU0YX+MmQNEq9RXDe3jA6PaE6+lkSM0ZjkK3huCUJiCc7zH83w3uS6+vwQnD2PUC3aTqK+WjwbacG7Y7BxcKaBZ2FEn6VfLGPE34xiQ5kw49a+JNU1GMGVsI98JII7B4usIYoI8y8Lc3tdACByzIBzpVRaAHbiv0ytm1Oollh9tKOF7Z1+GCf9G0/fg/BvRCY9ndDdi4/39wmPv/fe7/9zr78z+Pkp7Y+I/E1vgA61dLHuYh/CDs+1PEDZ/IQwCm5CSIwtQ1MjXURInu9DzM1WHpGFc/pZciqI8KmtemYzbWUbeQaKnFj+0irT3ef/K0Cf91r+O+EeAm/Ae8z/F/0ML4D4eBPf4/Qnoq+F86h6bABiOdP/FMTrKM8DhdZP+W0gb4/DC+nEhB8u7Gu9WQ/MGrLXS4obbom4T/hGz54Kjn06odKEQFqwa3ma0hIXOQUukvbZH79JhpA/7nEwMPOA68Hv/5zJ88/3HYbvf4/v/B4f7816Okp4j/aI65i36SmeATHQhWOvBYegYKNe2F7UEuUFyyNAVyW9nMR3nbkRgz0FumcbYUoKbgONdqs1Yng3L1Wq1wil27gn9+A8NrTaAtRKrudK6MMAojZCVay2DSNlupRzC2zahzzdJ50assNKLcpfQX60qSt36A5rnAmySMGmfUeM5ZYzO70x8A5XwvlRCSHzBWSopC90jbA1bKqgZHTdKX5TzZzipNjfmcNegg9hxmiTOHIycGmw6meoEoDiHTjKbatmmjZsOzsaIEQ5pYJolTuioTnm2UZEuM8VOPOvWKTH7BTB5oKAX1afPBZXsPTReshNh4/py625UAM1ngaVCZaefi6Rj6y31LxxC/enMKuvBENy2WV3221gi9uT2lF4BKwrfVzLD8ZriDeVYashpsb8bKtQE6dGkA9Tm+KU4BXIXXFPowWmRWt5PGgHTHMBbgSFIrR94nR8XsqwUsTQ+BCYS8nG8zVv80262q+on2LtPJmpLaeYwVepYHimDkysU087FJPyijdYY1OlqhJ7ZSSe1OkTI3o2L/549wjAiZB311CQWGldeJPQWqpTNVheMsRrkWNNaLEDrSsqBIQS/KXhb5o8GiKK1S19ujN6eji6Pj08JbQhZI9e8AccPSCyJOyWX7hGre4cAxzAYnKxv8K+rWYJyz/56jGp4guwG1lxov5/nszdGPp+9Pj6/OLz+cvz+9/OXy7KqW/yERB5LYh1DRbPKKtAd8RKtwVhpzahhWALWKyR+PLk9O3344Oj4+HY0+XJ3/fPq2nkWjubDjJqBbUy4xNkvYJ/5s5uBhO+DAMDNBDDDWVT46PT35cHL+5ujs7Qds6BUMaFZU3IGMmGrJxULLDefQ50oWWdw+7eLu7PWe4fr95dYKpecVrNc2F/j86N3VT50PF5fn//jnh+PXZ6dvrz6cndTLDqKvpL3GDiqPIahnen8wiWGav9uR6dIF9b8veg7aaz+cmj7P0qm8F47X901QWbM0b1HJm4Kfr2/N+V5r09oDSBUK6ugQ5mam68WiYvl4ZXZU//e7xQMraaGnpDMuh0bhQf1B0EUtlq7DkNpRXmXmTsEzxPDb1aVaz4sFOY9y+Xhpik7K2QzKfuMK41j5cCc3VjIiM1aUVXA3VymrwoXvLaC7M3YRh2NaBHS8eelHmpRRPuLg3pxR209mv5dfci/4Zetlu/SCQRSC/fSnq6uLwisv8BLP9k+obwMagJm74BcOWoU8EQUnwc3etvW3YM+udy8JsOTyMwnQbxRJsvrBVxp+qarMu7kI5VnatR2iLEEcJqET+kNydVzk9B4Wl7Mqc2/Naq057sRqxVbzXQub/LYs5xqPbRH66Zy+QWe60jrc4RZejA6CJfaFYjhebihfQu96OnqYXTa+dCyorSP0AIcqQ2qTl1rwUmbmIpW40aWruFelvNjJ8ILJQqiS8/twN6veK1rD8UOcrfX8V6LOIHRpdgA8y6Y/fVC0WakPZwkBjTTXXz35tPUkoU/j8nyO9vBBtSVhFIJXtBxFaDsQeeGmLa/QSaGD2beja3oDY4HWJKrkzxTMrXhWfBayhB+CzHPjbavvAgYcs4mHCDgkI8B4N/XpUbC8sZf6KInzLNU246ZVnefThb/3NE67l6tEQFVNrFvEnq3OnefsyXtUqVvkuxZjsUrRYeqCvi13O6w51aGLoA7I5vTpPEqWJ15Z89T10vmQvKFziK6LJIqwYm6A2DrJdjmvUpnurm2PTYC8OxgLed7YUZH1+8zRbwH8cpLiDcDXkPQ6rXUa3wLEtwbwTa2zgcCTPDC7Yf1Pa4zPd/6z1R/k+z8O23z/f2d//++jpLXrfw+8/vEB+/9XQVTtNpFjhT4PXiBcCT67Lxve95qcGgjf9bocpYHaCUbcaFKerC0rGqOkfBnzSeLWPn2atAH/o9B1PRan/NrvcepO6T02gmw6/3nY0/b/HfZx//dgv//7cdJT3P8R8WWjfAfIReieZEb4AzfCR98K8oBtIGo9GELFd4HcCoJBHkaMj7BVY337b+r/clHU4Yuin2n/b7vfyvp/rzVA/6/XPtz3/8dIT6X/33OBP59O0AGEiemT/GibhiV68XoU2bSVYEsvT7+K9L6eXL42mN3jZNSzx3OKLy2IjMYKOURGoI2f7cHVAh5LD8nE9hktfuTDUMoivPtn9+JlrZ2hUJ3AlrH3HJ9+2oD/2WIjdDTeecFKdh4GNvl//cPc/+u1u9z/G+zv/3iU9MTwX2GIGzrXNBaB/f8ydZvuLkdEcsMGG0br3dLjE9tviyAtuBGTnL8CN1mEbZXfFICwToindoRtQ//HzTdyo8Hnm//rdLt5/++0+P1v7X389yjpifZ/fZ7+vv2+NAn/hY6AIaGVe/2jNI5CBhxxJk303SjD64bXluLe2JCIp42azfZyd4a87nf1UQO5GAVdIJybtR9924WaipS/vdOuVy2znpE2hmIX+8dvJeSei1NyTw0gv/K0Ef/FPp8HfQtyA/53W72uPP81OGxx/6/V3n//8XHSU8H/FSDPre/Pd+6rgsjaeZKV+DmJAYUhl++aeESFb9Yj3/7rzlC70wAyr44vjBcGvjOGd3d1u/E+fvz4729zAbbdZbc1g7bvm8Ir5IeRTHmK2JQnYHbiW9+al/O9NStinvgL1hyFrsmtwMzmcckK/WQtou1P2Ka6zG6zKqSI2lwxCGaUPhCin3gAJQiixk6CVoUzc2ZswABkJL/fCQlX9mcpw7TL5+6gD9bsxuqVr/nI5s6Fi1CzARVfiFLa7lZT7p7dcsOqaCKxcbS4wbJuX2h1w+xOHa2Gt3U7VFdzoO+DLRhWcU3hQQsIvf3U3VeetvP/lO9/Pzdw8/6fthb/H+L6T7+7n/97lPRU/L+tPodSvuCr7CiqW6l29xfXnH19XM9x1RCqNFEZSSuu5oqdztWxdYsDvfsFnK89bcD/RWQ/LPbHtAn/D3v5/s9eF7//e9ht77//+ijpieI/2p3wn90S5tdcXNtctA05ELyXt9VehO5Rdlvtn23+IAt6eFySnW+vuyIHn1euycljhJ3FrAw/2BDiGmH9ML/+ZLh1MJdPacuSnFPt5B489PIDH2b+Kjv98JcVNypk4OVe1p3NA1JRWvh7Xj2rUZF77gVHYm5Bryp/ukrydmuLi2Oqtdm3dbVlT3eubavBewP+yzD3s87/9jqtbun+/1Z7f//j46Sngv8FcFtzU3q+k+uNvB/9F2Gix4UjVU/mEt8aB33ljJs3DcK4eL3T1ifpyl9DER8uNR3bxAnLnc7E8U+XZocPNBSRYCDvA77X+Qq8mb8ktmCf33wh2lABt4x8chy/9wEKVXjzAC4n3cQBXU6dX8NPzUUbec9z7DK/6Ng/pIHrS0myDz+IgSiMssOqeNX98eXp0dUpfsTg3cUJ/pIX7UsHoOZDCPKN7D3y0v62/rZ4ob/+cYTKQKTwPuQ3P5ePDBefrg03BzX2s7bGrH3KlVZe3Kte5rn0dDLh11mTt2FAz4OTeHmZiuN5GeJc0oVHbzJdZq0kXa2YesEidHh7Ke/nbPKWUpfvL7pnp4DR/0/bKYD3p9QpVn/VYtdusv67F/uO8+k6zpd2gf6rU63/vxAW9uCJH5nW+//tXrd3KPZ/9AfdTr//Tas9aHUGe///MdIBkScAxD1kYpN/3QjSaIibBXkUr24SHBKaxgDWptjqakXXU8uli+wqE1Ne7dCMxciSX3LSzFeOmyt2nkXa9YKAFWFyAQgt5jcOCB5WjQGaGD+RwFkjeIXhzSxkNLvG0BOv+d0wOGci8cnikytT8LQXLattdQ0pnH77JvnXvxuIoKoiyGw01DBaeNjIdZjdw8tn0rMDE3UCkvxq7UZ+u2+n0ShO+A+5tKOIOhg3MbwsBChCOKY8ASLX5gibhanvkjGIyyMD9CHEr+zKmwOiX4CbhADfLv4PeSyRKwUu+P1BLH8FOfn5jnBSVwqJpeBA8LxnEwIEIEvCY0QZr2CTADcvQAJOCP6eokEgx1AWV8qRsNJ0ds9wFsihxrVoZbWCtExV5WBUVYqZkJVImBi4KsJwxHdReBW/zGggTsm8WN2ogjp7QWJUHbCDkovZMmGKctTWmWOW1lLiGE6dqgvicCO9h7YTRRReyE5CMxPIdM79DCO7DS/xGb+MzyAshfD/tlG49gJaI/96zJrWEJkIftVmO1utKECn8PkNrdEoXhjN+0CjemEtf35AJkx+oacDYxr24rpMjh2Ja8D5NOcBOEYuwKf4ZZKj16/hl7qo6hIGHJyWYUuQei71Aq/T4IiBH4aviw/fMZxXacvqszBBbJ2RXwU6u2goP73d6vRbNd28UbjdzPfmntpW40QpF2/O/xIzqPCgP3jj8VGBb17W87bLedudl5C3IbeuYM7iJpms9bPb70CWwvk1YWDV3iJPykGN/M/yXnBtYGlAyJLX7OpECtPa/Ima6hZ3zRi4pmDIF+DwOgn3fPmBO/7xRFUIW7P4absoxfBF6IF/3+5ARh0wNgVTqhEZkis+7/+TN4WecwWvL6VmeSlt+llS4aruc00faLoe9HizHOhTyHoJ2ZAHlaZsFO4FQ5PQb9TCcTG7zIvbi4QJJF6Kc8SoUY1DeDEYw89OjskRNA85Vc4AKU7jHSi7NW9gtM3PG/ILhxqVb6VIkhdxuIDscZEY3hKPByjHS9yjp76PUof0oC1xfTCM43aAKKWu0IDqeXmsHwGQSjIoOn6UqwNV38p1DcnMyAH/SERS+AuMCP4NPJfQue3J61NlVhHvk7OTEquCNG4Fu0VMLXL8AjNDJieMweKiMMjgHAwfvYpE6SvXhKSA3QOpcmVpMw5nLh9lq5zJYedLcXdAAOIYufj5+FRxhHXjnLIkhFepqbFAE0j4dGWhQAbock5C3l2+/oIyjUIYfDhD6gWDcTbicyY3nu864DEzfoMoGzab31n4AQh+AbJcA2sKZpsO8DS2nWsZbwvZ3sV+WWxVC4F3uVpdAl6rjf4PDPAoj3VDfd+8DsKboCks1iyK5Hpg0NAvlnxmSExzgHji69t6vYz5ZwEfD+no2kMf3Jssc9jFi0vF23MojjkECZ5PanNdbhgLHW0owI2wl6CHQk/EhwIM0GvgzYyPTPyaHsYot0sUWToOI/HZuyN+fEjMaxD1xT30GrzACef4I85xmcMGEV94gpa2edP5CB1zO0ZzEV6WLQ3SmbuW5Ec1LIZO05BHT3KlQ2Q1p2EzCUOfNbOiTRgrm4v2gaDAa88FHCWx1uJHwOSExhRUJOqXXViurCK3WFRaaxaw/IzKufzhiGMpKKdGJSyHPu6s4T5c6BF00bZEd7vMKlYiTsGtTMcWaK+Zb1fmwoz9cNyEWKzz0gJDBiogHv8QCgOdHLxut9q9TMyMOg4j6P3xVRPu0GvNnPvykkF0Ej3hjHJ/EsNEnon3BpeLXbaJlEmvXYgKXon7LatESmLMQM+FoWt5fETGfGYTO31E56jUORgENzxogwW3/yx6An48viyWLJEx7KIN0ZOOj+QMqWhObmCi9bh/7tiWAxBxTZf5OrlgtsxI47EaSHC9poF0sYpNdHCScgutYWUc24Hze7PUOE0PUYI1O/1XhP/kxgtwRahXbOXkhod2NnTFAHw5/ABCyG84kC3nArxCIOzhI9uX634K0vOWzwIE7O/ZrTAfa2nYxTB7DaGS9/0gWiJkkrfj13o7kCkfOyDC0T4SdyDdTiJvJ5VrGap75+/yDyhIo8K1VjCq1/rVpGtgDcxpbjszNNclvsYHjJ9YQEwrUFk3jZ3xJJriERmquYNVaB6cYlupGuIGGA2oPeehzAsScgSGTHLQ4BaZOy84/oIfoYYZ6lqcrnYyYXM98qQAeYaivuDyPlelzk/Oh8KHKbvEYBzK20Cjw+Erw4/8yo+sFuiQ8zSQw7LOozqnUGwc+ckGCLbwEoko9CQey+dqnUDFcwf5MK8RQf9MOCYv+DANuoTcAY7VskPkRv0CYQY9wDJ2392hIX38aIof3KKyxSi8lfeC15CNnVr9+DbThJIIqnG9CSAowQV2/uruLqfz8SP5GzzIGSvUNSxXoajqnb1cY+lYbt6uqv2CqRfcZl/JKJ4IQs+QBq6Znycx8AL5kYF+n5wJ4toF24S42GMz0WOUhoWTKcdFXBMCt1SyUZ0nlMy9Hslj2lwUUBOGEAwsl8bgP+l33yY+y0eNjMB5JCFQNiH3nosfAcvyniVZkCbbXU0X8cjx7q5QLl+FLIaQEHCegetuMz7ppHa1gMNPKYDyHAhmJSgEG54z04I20BR4UmKY5/XzF2hsVoN3XO5QiEAhUxkfv/+Tn5fOp8Wrp765O4j0/gP0INSJBbHs6h/8ww+nuGpZmjjDklZD/F+ivVqrhlrb8OfrNeXkpEEWG7Zb3UF/8tIx3Vdj2+z1Jq/Ml/Rl3zzstelLx2m1J68cnKRRXzMRKDOmeQgkdQNRcKZOAL+kNkYqsNopMUOG5NVLuzsYD16Zg/6rjtkbdG1zPGj1Tbfn9Afdyctxqz3Y717fp33ap33ap33ap33ap33ap33ap33ap33ap//O9P/G5ujqAMgAAA==
  values:
    replicas: 1
    priorityClass:
      name: gardener-system-100
    clients:
      - name: local
        clientId: local
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller@sha256
      tag: 22889df0d9351aaa46387c28d9ac7a5bef0a05ca1cd7051247aaaef5e12c105e
    imagePullPolicy: Always
    webhook:
      namespaceSelector:
        matchExpressions:
          - {key: "shoot.gardener.cloud/no-cleanup", operator: "NotIn", values: ["true"]}
          - {key: "gardener.cloud/purpose", operator: "NotIn", values: ["kube-system"]}
          - {key: "kubernetes.io/metadata.name", operator: "NotIn", values: ["kube-system"]}
          - {key: "gardener.cloud/role", operator: "NotIn", values: ["extension"]}
      # TODO: Add the moment there is no single label key to identify the components which should be
      # enahnaced by the webhook. This setup is not recommended in production environments.
      # For production environments, there shall be a single key on pod level and each component
      # shall have it own value
      # objectSelector:
      #   matchExpressions:
      #     - {key: "gardener.cloud/role", operator: "In", values: ["plutono", "prometheus", ...]}
    vpa:
      enabled: true
    configuration:
      oauth2Proxy:
        sslInsecureSkipVerify: false
        insecureOidcSkipIssuerVerification: false
        insecureOidcSkipNonce: false
        oidcIssuerUrl: "https://dexidp:5556"
        scope: "openid email groups"
      oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVT3B4dzVnS0MxdDdYdW1abVVzNENIZW5kek1jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd016RWVNQndHQTFVRUNoTVZaRzlqYTJWeU9uQnliM1pwWkdWeUxXeHZZMkZzTVJFd0R3WURWUVFERXdoTQpiMk5oYkNCRFFUQWVGdzB5TkRBeU1qSXlNVEUwTURCYUZ3MHlPVEF5TWpBeU1URTBNREJhTURNeEhqQWNCZ05WCkJBb1RGV1J2WTJ0bGNqcHdjbTkyYVdSbGNpMXNiMk5oYkRFUk1BOEdBMVVFQXhNSVRHOWpZV3dnUTBFd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdElNR1R6cnN1cUdCbXByKzdidVdEU2o1Lwp2T3FwbDlwNWhsTWNUaWR1eHFpNmtyc2M5VWZDbmRKeEUvV0hDZW1POUlqWXRTVWtBeUtvSThuZjVTVlN3Q01rCndVZWVmVGVnK2laVUpseXdvTitGWHZUL1Uya2lYSXRDV2hNUUwvWmdjWS81OVROS2FCekdJZkY3MVY4TjVsM0kKSkVTbEt2UFliMnZvV2pYNXdiV1JteEkvSElTaEhaamhBK2htSkZBM3BBQnBQZUFvcmYvanB0YUxIdFgwQk44Qwp6N29uMmdYTzdsUVN2Sko0Y2F0SHdXeFRTQjhPRncwNXZiQzBTaVlmVVdUSmc0bFJucTZhazhicDFBd01TVGpIClUwMGJzU2ZXL0syeVNmSVhMMENHdFVvbG45K05icjdIU3ZvbHRYaXp2MWd1UHR4ZFV6V2t1ZGlqc3prckFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlRIZ2lvcjhzR1hweHExTCtwblpqRS9wNTl2M2pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxBZGVwZjZICkFNSjFMOWliT3JONjV1RmVISFJPUTZTR3BjUURxdXBqUG1CU3Y1SGJsb2kreTlWalE1eDQ2dUtRdGoyTWJlTGUKVGhrRnA5ditsYkk3U3JqRjd4R0tOckVHcVJzanJzdGhmb2FDdkZQU3QxMWEyd0ZGeHdsVmsrTzNPWmNhRERaRgpNbXdGbmJmbXB2bHpyZzN4U2wxVkdnL3BiYmVzTGJoNTNyQk1ndldkcU5JYUtIWExoYXJSMXBYb1A3NjR6czhECmFQcnc4bFNxaXZqWXJJelZVUzllUDQwQTJLMU5vakJQVlB0dldXMXpySGMzb1c5SVZOS0EvaXFnMGNMdzYwN2kKblJ2NXdDcFlKTThKTDVYZEZ6N2NPTXNNUEUxaElYU1RDUnB6QnFZeUFFV1hEeXl2d1RmMHJBQmZzTDlzUVVQRQpYOTZFVVJsbWVsRW1nQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden--plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-seed"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: prometheus
            name: seed
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--aggregate-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: aggregate-prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-cache"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: cache
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
