---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1d63PbtrLvZ/0VuPQ506THpB6W5EQz/eDaPq1vk9hjOek50+nkUCQksaZIliBlq27u33538SDBh1524jg5wnRSmQQWi8Xih108lqHnOqYdRcx0wiCJQ9+ncfObj5takA57Pf5/SOX/89/tbq/f67c7HczXPuh3Dr8hvY/MR21KWWLHhHwTh2GyKt+6919oCuv635pSf+ZNgjCmH6MO7OB+t7u0/3vdHu//Vq9z0MXn7d5hr/0NaX2Mytel//L+3yMXdpLQOGAkCYnoc3IzpQEZpZ7vesGERLZzbU8osxp75GrqMcLSKArjBH6Anvhk4ocjMrMTZwq590lMfTvx5hTKJVPtuR24QCCgE3gbBuRZFNOxd0tdcuNBvv95bpHzwF+QMOAlkSUS0Zj4XkCthnUyfD9MgDcgcRzOZkDg3fGQuF7MGtbES5r8X8F+wxr9GTf5v+rBdNLEf9SfbB40c0IjaF8akbHnU9b4zmI3Efw7sq/h32SGv0Og0/ju/6DEOzv2wpSRs5NTqDeKw9+pkzQsz6V2U2SHRw1rzpzQpc3GyAsajPmNz93JK1Lt+D+e2nFiLeyZ/1HqWDP+252Dw/L473UPduP/MZIdee9ozGBEDsi83QjsGR2QOqVouJQ5sRclPOsR+QmmCOKgopBxGJOf0xGMWJrAEFIwAf8lUyrzzEUllngl/yJBOoNigCNh6rtkRIkXODGd0SABXKC2MyWJN6NkEaYAJNecVgBIBDUAWOXEAVqIB3iU0FkE4EPZPhLyUw5fmA3aknGAw1j8ZMQGsKO3EQxiqA9IjqGp4Q0Z0pkdJJ6jMiKZZ9Mkidig2WR0BqQAFCbN5425kl3LalntctNLzQzHihnfcwQKjijSdmnkhwvqrpEOUN9MPko6Wk1WsdFBmOgNB8rLm45c0YViA1Dbh2KF9pVbBW1IGZYEumcJ/hlTB8CWBq6Qc8qgqxOB/H+kYYKTCxDINNGYc3kaTxk5v45Ui/9u6FiT8KPVsc7+6x6W7b/uYbu3w//HSM0mGV6c/Mv8J1g/x2G0AFNnmlzR22RAOq1OmwyPLsjwlADC2wH/wx6DoeQByBIY0ZEdLDj6/mjHLg0ArLgWeaMUbDXWaDYbiv4rz6EBo+YZZEu8sUdjmETAspxSs2O1GpBvEg4mSAJJsykxHWJYVhP+m4J91lSvNDU1YzrxWBILfGNTA6mAOcutVTkz0MAegVlHCsSF+cqnLflQzRNOGMcIbnklpFBJI9Kpfw3oVDv+s3n046wEbOr/9/sHB10w/MD+6x+0dv7/Y6Q1/f8ePDzwwpiVRPf3Bdbg/2G71VPrP6ABnW9aHdCAzg7/HyPtrYL/7sPgf6+xtxH4m6bZuLtrftc4vY2QGiIxOiLKYOZgazW+a374APlMMJfHXkCJkesuMAwVIEJjOYOYeU479RNiCY/2DRK13tl+CgYn5jwHCzYG7538RZI4DRzSP+A/vdkwhYbeEsM0iKQFxiv+FJwexxRlYGc1jFPfX4Ata/vYPpd7HFiD1fiFCto8f4I1YHsY2POOjXYwC4Gp3H0SLQcavitMdd+bedI9SdA7eDZacKmcvBliXpy6GBjyz63G2RgXX6jNpPiwM2wPLH4xF/Jn3Or2ffS1oHLgEyrhzEtuNxIy5i8K2htnclUvM9nKLEvfbyJ7n2V0/sbbMfh+887NecwkIohYl0Jcoqzis/BwS+ai2AuSMTH+zsy/M6NES1S6uarV/ywooNazOHKUQ2Yz0btSVUQu3x5Rf8Me5iXy7i03S5e4+C1dN2hSDM6s7QDdfxjEeG9sP7TEqhznlm3Grcgr2MWlazAGm7wFA3J3J5cCVjfUEqyszssoer5h/EpWZ2maJcVwlDmx+A7KW9fZyLa8sJmtF0Bd1SJ/CWe4JJYqFXDRwQh1zdFCEFJaNqTxHKC2VqxDyfxWgi232KxlRywarZOeAAyrvkUwJhM7cGixPfqwLOoIjXEe4Zi6TXucvJzepHWs+3qHV5nHmTAMYGobEK2CpWO2Mr1pjWHUiWkil0i2btOQl36zDJm1nJYjeFGYKrE0J4AAWx72z1YKKZ8UrOfEuKGjaRhem4kPliXVsUTBdk2ddYyy/HUN3ipihvwBkLMCRSvdoIs+pmMaU9BB7hjyt7bpBb/zAbB1V1zScR18NiuzAosQLFeLFl6xhMaXoU/fKAmba5qmaxiTuGA7TpgG26mXLHskii7VrWK2knqpXtpCgZbQDTbWg00IrFeQwjgVvUDASaLbjdBy933l8rukSYobijaIzANYPOOGCKNgkGDxDW1MmjjTY1n+h8UQSufuAx/jhHDoEnUozJoAeirWJ9IrsbBqyw6CMOHLOEyr0cpq1PI7fpi6TUHYFCIt13d2grUZ2osYl95zCOO5mHgtMkBv0z+IkKDOtcxSJv89sTLxmYU8I1CO6+yZJv6aP2L6R+rFIPlnHISIMYZuhH4ISVYRwh1KaECMJaLjLD/XeCuBz+d2Ynfp3mnN+o8+E997P3jd/m+v1c3XfzpdXP85POzu1n8eIz2d9Z91pqrwPfLdasxiCk8o5q5Vu3HtBYBimnPQmNHEdu3EHgAcbuamaLOoQNFAGWlV30TYbjyXcBEGOdivtOeqbogFzl8A7IOASBdJ4poOknMDxqsSpM0t+bfY3Llfwbu7alM/DT1lH1l+6Ng+UPcYS8FcomPRZtGrZ/whf7BZR1aNZtFTuUOxAY1638oqmj2feww/JG2O/6JX7jMLrNv/7fe19X/M1+l0uq0d/j9G+grxXyLFlw/9jPrjoTcJ0DS/+0SAs278CxBFl/eT2X+dg9ah3P9tH/YO2zD+263+7vzHo6SnOv7zyXvZ+I9HtmPZaTINY+9PcTzj+gUrWoI5lXvAwTIDYqvx7i8b5HHqC6POJNCqH+MwjdiA/IpLCr9x0jFlYRo7VDyVyzDM2DeEAYO/6BzXGFSBOY1HIvN34lGZMrJWT10cQJxxalBBAvIGMGS8FmLgjg4gFv9z07oCmtyE8TUeAhS9Ul8xvIcHjG5OuJ5OhtSc4Sh0awhOaAKN8z2G/7vBc+n1NThhGLteoKtUfaV8NtiUc8N2Z2BCAc3CiSJJv0remKUJP5gkV9JhZI29SSqKMWODxu0baQQaT5coA4xRBvb2uh6a44QF+UCmqgiMwE0bvXR1ra7FcsBt1Dhe2ddhgn/WtPn8PwL0QmXZ3gxYe/6/f5jb/z1u/3c7u/s/j5Ke2PyPxFbYAKt3Sx5mIfwg9Ptj+A0fyUIApuQiiMLUFW1qqIUS3eh5mKnD0hHufkorRVAfFiSvLcesraNuI9FSmx+beVo7vP/oaR3+61bHfT3AdfgPeJ/jf7+F/h9OAzv8f4T0VPC/dA9NgQ16Ol/wSk6yiPA6XWT/kdIG2Pwwv5zIhuTDjQ+rAfmLV1sYcANt0zcJ/w3Z8slRz6dV21eICloNZjNbQULmIKXSn1sjd+kx0xr8zxcGHnAdeDX+A9YfCPzvw0xwcMj3f/uHu/P/j5KeIv6jOuYm+kmmgk90IlhqwGPpKQjUtOe2B7lAcMnCFMhtZSsf5WNHYs5Aa5nG2VaAWoLjXKvDWp0MytVrtcMpTu0K/nkEhldagzZoUvWkc2WGURghK9F6BpN22Eo9grltSp1rls6KVmWhE+Uppb9ZV5K89QN0zwVGkjBqjFHjOWeNTe1Orw+U87NUopH8grESUhS6R9oZsFJWNTlqLX1RzpOdrMLkF0T6QKEWqtLWTsu6EZouSJTYeFebupuVAJHO8eakzLR18XQEunXf0jH4et6Mgiw8odLF8kq/azvMm9kTegEjWNiBWpeV3wy26MpKR1Yd0/W4stKZBfUHAJzhm6K7fBVeU9D3JE5pVreTxoAKx4CbiLq17cj1d1jMvryBpaUUUIGQl/NtxuqfZic7BZHCu0wmK0pqdxeWyFlevgGUz5tp5jiuXyrRBsMKGS2RE1sqpHanSJmr0YAYWsv4I8TTkHkwVhdQYFB5ndgToFq6f1S4+mGUa0FlvQhhIC0KghT0ouxlkT8azIutVeJ6c/T6dHhxdHxaeEvIHKn+Mw5ng9ILIm6UZWdqat4hyA4yILeyibIibm2bjrP/jqMa3ra6AbGXOi/n+ez10Y+n706Pr84v35+/O7385fLsqpb/ARGXd9j7UNFs8oq0Bxz9K5wV1K2WYQVQy5j88ejy5PTN+6Pj49Ph8P3V+c+nb+pZNJpzO24CujXldlyzhH3iz2YOHrYDkz0zE8QAY1Xlw9PTk/cn56+Pzt68x45ewoCmRcXTuoipltxYs9xwBmOupJHFo8YunmRebUWtPottLRF6XsFqafMGnx+9vfqp8/7i8vxf/35//Ors9M3V+7OT+rZD05fSXqEHlcfgADN9PJjEMM0/7ch06Zz63yNOG3Wv/XBi+jxLp/JeGCnfN0FkzZKPX8mbgk2sH2P5XuvT2ss6FQrqmg3mZqbrxaJi+XhpdhT/99vZzktpYSwFnXE5NVo8xsJfBM25Yuk6DKmd5VVmbhQ8Qwy/XV6q9bxYkPMot1oXphiknE05z5U5qihH7UPfm8NAY+wiDke0CKUYH+hHmpTxNeKw2pxS20+mf5ZfhnhH8UXrRbv0goGtjCPkp6uri8IrL/ASz/ZPqG/DOAQFc8Ei67cKeSIK07ObvW3rb0GTXO9eLcCSi0/UgF6jSJLVT3tS5UpVZXbFRShvfK5UxXIL4jAJndAfkKvji4Kg1M70Onsjy7nC0piHfjqjr9EIrLSNG4pi9tUHb4lPIQE+zteUL6FOPR3dlSp3XToS1FYReoAhkCGMyUvNeSkzm9pL3Oitq5gFpbyoohhEsGBi5/w+3Dyon81XcPwQI2E1/xVvKQhdml3yzbLpTx/kJVXqw5UgGMuayaqefNx6ktCncdln1x4+qLYkjEKYzRfDCHUHPAY8mOMVBikMMPt2eE1vAEm1LlElf6agbsX7wNOQJfyiW54bI2q+DRhwzMYehiQakCEgpJv69ChY3NgLfY7B9YFqn3HVqq7l6I2/9/JDu5uLREBVjY9WxJ6N7hbn7MlYmdQt8l2LsVilGDB1zsqGO9orTu7rTVCXIHP6dBYlixOvLHnqeulsQF7TGXiFy1eFNHEtgdi6lm1zJ6GypFnbH+sAeXswFu15bUdF1u+zDrsB8Evn+jXA14B0O61VEt8AxDcG8HW9s4bAF3cpcs3+j9ZRn+7+X6vXz/f/5fnvzi7+66Oklfs/Dwz/94Dz38vgq/aYwLFCpgdvEC0Fpu23je4bJqUG3rcNl6IkULtohgcNyguQZUGjq5RvY31xmLZLm6c1+B+FruuxOOVhn0epO6H3OAiw7v7fYVc7/3XYw/O//d3538dJT3H/P+JbIfkJgIvQPcmU8AeuhI9+FOABxwDUHie4kW8DeRQAHUD0Jh9hq351/68b/3Kjz+EbfZ/o/Ge7l33/pd9t9dH+67YPd+P/MdJTGf/33LTOlxp0AGFiaSW/2qRhiV68HkXWbY9vaOXpoSjva8nl+11ZHB+jnj2eU0TaFxmNJe0QGYE2frYF1+G5nz0gY9tntPiRB0MJi/Dhn8VFy3o7Q6G6BlvGznJ8+mkN/mcbaDDQ+OAFLdl6Glhn//UOc/uv2z7g9l9/F//hUdITw3+FIW7oXNNYOPb/y1Q01W2uCOSKDTqM2ruhxSeOXxZBWnAjFkB/B24yD9sqvykAYV0jntoVpjXjHw+UyM3zT7f+1zk4yMd/p8Xjf7V3/t+jpCc6/vU1/PuO+9IC/We6AoSElp71jtI4ChlwxJk00XajDMPNrizFrbEBEU8bNYet5bkHGe51+VFzuVEFQyCcmbUf/dqGmvKUv73TwmuWWc9IGwODn6/68K2E3HNxS+qpAeRXntbivzhB86BvAa7D/8N+W8N/fv+nvbP/Hic9FfxfAvJc+768ez8VRNbuSCzFz3EMKAy5fNfEaxf8GBz59tc7Qx1RA8i8Or4w9g18Zwzu7urOuX348OG3bzeuMxOLqdYRZZ3aUiTUZJS+P6AfEgeuBFFjq5qj0DW5BLOazZwZG1QMGcnDxyDhytEg1W67fK0HurjmIFC3EiNZLc2KGajm5CC+EKW0Y4mmPPa44UlDcc9WHE4snu2rO3tYPulYXCF+0HJwt2YhZjP8V3P//aaB9fv/Ov4f4vpv72CH/4+Sngr+bxQOvxzgpTxRqKgk288XK+5zPe7MsQzjlCQqUFeZapacgqyC3waX1HYLuF97WoP/88h++HfA19r/3fz8V/cA8rUPD9q7+/+Pkp4o/qPeiW+3uiXMrwlc2Jy3DTkRvJPRCi9C9yiLVvil+Q+ZVcoNx+zOZl2IBHxeCZNw32O5ddMPdoQII6lfUNWfDDa2tvMlLVmyIc8Vq+s78NDLD4Ob+avsZPTfltwSzsDLvay7twOkorTw96x6jrvS7pkXHIm76npV+dNlLW+3VgYOWFabfVtXW/Z069o2mrzX4L/0Qz7p+k+30zoofv8Xv/+6W/9/lPRU8L8Abisi5eYnOV7L+Li/CBU9Lly3eDJBHGsM9KVLIt4kCGO82p1fPN74lk05Gr74cJ3p2CYuK211X4Z/ui47fKyhiAQDGQ/yXuerMTJzqdmCfX6bW/ShAm7p+eQ4fu8D1Krw+glcrsuIy3ucOg/DTM15G3nPc2yzAOTYP6SB68uWZIG/xUQURtlFNgx1fHx5enR1ikGs316c4C8ZaFkaADWBsOUbOXpk0Oa2/rYY0FkPjl2ZiBTehzzyZ/k6YfHpSnezX6M/K2vM+qdcaeXFveplnktPx2MezpS8CQN6HpzEi8tUXN3JEOeSzj16k8ky6yVpasXUC+ahw/tLWT9n4zeUuvx8wT0HBcz+X+ygAN6f0qBYHtV822GyOu75buB8vIHzuU2g/+pUa//PhYY9eOFHptX2f7vb6WbnfzqdXu8b3P1t93f2/2OkPSJPAIvYOuKQb90M0miIaFnci1fRsQaEpjGAtSmOulnR9cRy6TwLc2DKa9/NWMwseQCEZr6111xy8iTSQmYBVoTJBSC0WN/YI3hZLQZoYvxEMmeNYFium2nIaBaayxOvedwIXDOR+GTxxZUJWNrzltW2DgzZOD2iHPn1twYiqKoIMhsNNY0WHjZyGWZxGMV3ltWB6boGkjy0aiOP7thpNIoL/gPe2mFEHfSbGAYSAIrgjlU+6symYeq7ZATN5Z4B2hDiVxYOY4/oARCTEODbxf/VfCO65Ljg96ew/NVGX5a2eN6zMQECkCXhPqL0V7BLgJt9aAEnBH9PUCGQYygLEzcnrCSdxZnMHDmUuOatLBdQ4bvqZeGgV1XymZCVSKgYmCr6J595Fb9MaSBOye8v71RBne2TGEUH7GDLxWqZUEU5a+vMMUvrKXEMv07USz8Tv420s29awws5SGimApnMuZ1hmNVvuLMU3P/bRuFKPPRG/vWAFb2hfz17I12tCKD6/e1PqWiNRjFgKB8DjWoQRv58j4yZ/EJDB+Y0HMV1mRw7EmFg+TLnHhhGLsCn+GWSo1ev4JcKYnMJEw4uy7AFtHom5QKv0+CIgR2Gr4sP3zJcV2nL6jM3QZxtkF+FOLtoKDu93er0WjXDvFGIfOR7M0+de3CilDdvxv8SK6jwoNd/7fFZgR9e1PO2y3nbnReQt1G4kSJUpqr/8u4L0OB/lk93alNFA5wQpCI3DHQihYVq/kQtXovIEgbuEhjyBZiwTsJtWX6Fhn8OSxXC/il+rChK0SERLeNfLNqTfgTMNsGEakQG5Iqv5P/kTWAsXMHrSykrXkpbUJZUuPB6XHZ7mvT6XS7oPX1RWC8hu2av0jmNQhQg7GQ9fg7OdFnoHq4BcuAj8ZLnIuYB6IuiY8FLwaR8dnJMjqB3yKma3UlxXW5PKaJ5A9NnfoGIRxdpVILfS5IXcTiH7HGRGIb9xRtRowWGlFUB7+ugG4QlYlzCxGwHCDvqTjxUz8tj/YhoVJLBluNXVjpQ9a3cqJDMDB0weIRrhL9Ah+DfwHMJndmejPEnswoHnpydlFgVpPH4zy2CZJHjfcwMmZwwBoWLwiDDZ9B7NBMSJa9cEpICjg6kyoWlLSGcuXzarHIm55HPxd0eAcxi5OLn41PFEdaNi8SSEMZNUuCuNUgYaeVGQRtgxDkJeXv56jO2aRjCbMIZUi8YTJwRXwS58XzXAROY8WB7bNBsfmdhRG8epVNuajUFs00HeBrZzrV0oEXb3sZ+udmqFgLvcrG6BMxQGw0amLGxPdYN9X3zOghvgqbQWLPYJNcDhYZxseBLPWLdAponPqeq18uYfxbwCY4Orz00qr3xIkddjPEn3p5DccwhSPB8Upp5bjxZeAnNLAw0fCjGOs7yvBfxkYlfP0Kf4naBLZIT/VB8puiIH/cX6xBEfSEJZ3kvcMIZ/ohz1OWoQMQXOaAjbd4zPiLDzI5RG4RVZEt9c2auJflR/YauziTk3o7cmRBZzUnYTMLQZ82saNOOvOa8vSco8NrzBg6TWOvQI2ByTGMaOFTUL0eo3AlFbrGoVMbMwfgZhXP5wxGHShBOjUhYjmzcuMKDjaDwdN62xGi6zCpWTZyAGZiOLJBeMz//yRsz8sNRE3ynzgsL9BSoQPN44HoGMtl71QanPmtmRh1nCbTW+C4HN8C1bs5tb8kgGnWeMB65/YduHc/Eld3lzS7rRMqklS2aCoaO+y2reDaZqMF4YmgMHh+REV+LxFEd0RmKdQYqwVUPemHOFTzzd4Ajj29kJQtkDcdgNliOj+Sqpt6lsg+5Ve3YlgM4cE0X+e62YLnMzKN2lOB9RVfpjat01knKtbWGnVFsB86fzVJHNfm3xFmz03spPvbOFRmQiVCv2OPJDXfLbBiWAVhtGJA75LeTG2JidwFJwYn18JHtyz07hd65FmTGPY79LKLDh1oadtFFXkGoZDk/iJZwd2S05lrDBjLl0wR4J9oHfvakgUlk1EG5D6E0KH+XB/SWioX7pKBYr/SQgysgDlRqZjtTVNoFvsYHjB8HR3wrUFm1BJ3xJLriERmqia0oJA/mr61EDR4CzAzUnnFPaZ+EHI0hk5xAuEbmdgpOtWAyqCmHuhanqx37Xl+PPAhOnmFT93l7n6tS5yfnA2GulK1fUA5lWKDS4VSWoUh+XT+rBQbkLA3kDKzzqI6hFztHhhAHtwovgEehJ4e7fK7W+JXntpfP/xoRNMWEDbLPp2yQJeQOcN6WAyJX6n0EGjT2yjh+d4eK9OGDKX5wjco2kjDa5gWvIQNdrX58m0lCtQiqcb0xoCjBzXH+6u4up/PhA/kHPMgZK9Q1KFehqOqDvVxj6Upd3q+q/4KJF9xmUduL1y3QCKSBa+bXBQwMqzw00MSTqzhcuqCb4AF7bCpGjJKwsCflHIn7OWCBSjaqa3ySuVdDecWSNwXEhN4CA82l8Ux+G1lmTnyWzxsZgfNIQqDsQm4oFz/gkuU9SzJ/TPa7WurhTuLdXaGc/j0J3VsE3/IMrHSb8QUjdSIFbHtKAZRnQDArQcGv8Jyp5p+BpMCqEhM+r5+/QGWzGnzgcuNC+ASZyPgs/p/8ruPSjx0r0xDp/QfogVcTC2JZ2A78ww8nuONYWvTCklZD/F+ivdpnhlrb8OerFeXk8kDmBrZbB/3e+IVjui9Httntjl+aL+iLnnnYbdMXjtNqj186uByjousLlBnR3NuRsgGHNxMngF9S6w4VWO2UmCED8vKFfdAf9V+a/d7LjtntH9jmqN/qmW7X6fUPxi9GrXZ/d/J8l3Zpl3Zpl3Zpl3Zpl3Zpl3Zpl3Zpl3Zpl3Zpl3Zpl3Zpl3Zpm/T/uIR29wDIAAA=
  values:
    replicas: 1
    priorityClass:
      name: gardener-system-100
    clients:
      - name: local
        clientId: local
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller@sha256
      tag: 70daa07294884a13b38cfd72b5d1e7880c13e47c72c45165a49921e8545c740c
    imagePullPolicy: Always
    webhook:
      namespaceSelector:
        matchExpressions:
          - {key: "shoot.gardener.cloud/no-cleanup", operator: "NotIn", values: ["true"]}
          - {key: "gardener.cloud/purpose", operator: "NotIn", values: ["kube-system"]}
          - {key: "kubernetes.io/metadata.name", operator: "NotIn", values: ["kube-system"]}
          - {key: "gardener.cloud/role", operator: "NotIn", values: ["extension"]}
      # TODO: Add the moment there is no single label key to identify the components which should be
      # enahnaced by the webhook. This setup is not recommended in production environments.
      # For production environments, there shall be a single key on pod level and each component
      # shall have it own value
      # objectSelector:
      #   matchExpressions:
      #     - {key: "gardener.cloud/role", operator: "In", values: ["plutono", "prometheus", ...]}
    vpa:
      enabled: true
    configuration:
      oauth2Proxy:
        sslInsecureSkipVerify: true
        insecureOidcSkipIssuerVerification: false
        oidcIssuerUrl: "https://dexidp:5556"
        scope: "openid email groups"
      kubeRbacProxy:
        oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVT3B4dzVnS0MxdDdYdW1abVVzNENIZW5kek1jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd016RWVNQndHQTFVRUNoTVZaRzlqYTJWeU9uQnliM1pwWkdWeUxXeHZZMkZzTVJFd0R3WURWUVFERXdoTQpiMk5oYkNCRFFUQWVGdzB5TkRBeU1qSXlNVEUwTURCYUZ3MHlPVEF5TWpBeU1URTBNREJhTURNeEhqQWNCZ05WCkJBb1RGV1J2WTJ0bGNqcHdjbTkyYVdSbGNpMXNiMk5oYkRFUk1BOEdBMVVFQXhNSVRHOWpZV3dnUTBFd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdElNR1R6cnN1cUdCbXByKzdidVdEU2o1Lwp2T3FwbDlwNWhsTWNUaWR1eHFpNmtyc2M5VWZDbmRKeEUvV0hDZW1POUlqWXRTVWtBeUtvSThuZjVTVlN3Q01rCndVZWVmVGVnK2laVUpseXdvTitGWHZUL1Uya2lYSXRDV2hNUUwvWmdjWS81OVROS2FCekdJZkY3MVY4TjVsM0kKSkVTbEt2UFliMnZvV2pYNXdiV1JteEkvSElTaEhaamhBK2htSkZBM3BBQnBQZUFvcmYvanB0YUxIdFgwQk44Qwp6N29uMmdYTzdsUVN2Sko0Y2F0SHdXeFRTQjhPRncwNXZiQzBTaVlmVVdUSmc0bFJucTZhazhicDFBd01TVGpIClUwMGJzU2ZXL0syeVNmSVhMMENHdFVvbG45K05icjdIU3ZvbHRYaXp2MWd1UHR4ZFV6V2t1ZGlqc3prckFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlRIZ2lvcjhzR1hweHExTCtwblpqRS9wNTl2M2pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxBZGVwZjZICkFNSjFMOWliT3JONjV1RmVISFJPUTZTR3BjUURxdXBqUG1CU3Y1SGJsb2kreTlWalE1eDQ2dUtRdGoyTWJlTGUKVGhrRnA5ditsYkk3U3JqRjd4R0tOckVHcVJzanJzdGhmb2FDdkZQU3QxMWEyd0ZGeHdsVmsrTzNPWmNhRERaRgpNbXdGbmJmbXB2bHpyZzN4U2wxVkdnL3BiYmVzTGJoNTNyQk1ndldkcU5JYUtIWExoYXJSMXBYb1A3NjR6czhECmFQcnc4bFNxaXZqWXJJelZVUzllUDQwQTJLMU5vakJQVlB0dldXMXpySGMzb1c5SVZOS0EvaXFnMGNMdzYwN2kKblJ2NXdDcFlKTThKTDVYZEZ6N2NPTXNNUEUxaElYU1RDUnB6QnFZeUFFV1hEeXl2d1RmMHJBQmZzTDlzUVVQRQpYOTZFVVJsbWVsRW1nQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          hostPrefix: pl
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          hostPrefix: pr
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden--plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-seed"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: prometheus
            name: seed
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--aggregate-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: aggregate-prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-cache"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: cache
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
