---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+09a3PbtrL9rF+BK/dMHsek3nKimX5QbZ/Wt0nssZz0nOl0cigSklhTJEuQclQ397ffXTxI8KGX7ThNKk4nlUlgsVjsE1gAgevYhhWGzLADP44Cz6NR45uHfZrwHPV6/P/wFP/Pf7e6vX7nqNlvttrfNFudfrv5Dek9MB6VT8JiKyLkmygI4nXlNn3/Qp+gavzNGfXm7tQPIvoQbeAA97vdlePf6/b4+Dd77U4X37d6R73WN6T5EI1vev7m439ALqw4ppHPSBwQMebkZkZ9Mk5cz3H9KQkt+9qaUmbWDsjVzGWEJWEYRDH8AD7xyNQLxmRuxfYMSh+SiHpW7C4o1Itn2nvLdwCAT6fwNfDJ0zCiE/cDdciNC+X+55lJzn1vSQKf10SUSEgj4rk+NWvmyej9KAbcAMRxMJ8DgHfHI+K4EauZUzdu8H8F+jVz/EfU4P+qF7NpA/9Rf7KF38gAjaF/SUgmrkdZ7bnJbkL4d2xdw7/xHH8HAKf2/P+gxjsrcoOEkbOTU2g3jILfqB3XTNehVkMUh1c1c8HswKGN2tj1a4x5tc89yGueSvk/nllRbC6tufcgbWyQ/1a7c1SU/163s5f/x3is0H1HIwYSOSCLVs235nRAqpii5lBmR24Y86JD8iOYCGIjo5BJEJGfkjFILI1BhJSagP/iGZVlFqIRU3ySfxE/mUM10CNB4jlkTInr2xGdUz8GvUAte0Zid07JMkhAkVxzWD5oImgBlFUGHFQLcUEfxXQegvKh7BABeQlXX1gM+pJigGIsfjJigbKjH0IQYmgPQE6gq8ENGdG55ceurQoimKezOA7ZoNFgdA6gQClMG89qC0W7ptk0W8WuF7oZTBQynmsLLTimCNuhoRcsqbOBOgB9O/oo6mgtmflO+0Gsdxwgr+46YkWXCg3Q2h5Uy/Wv2CvoQ8KwJsA9i/HPiNqgbKnvCDonDIY6Fpr/9ySI0bgAgJQT6wtOz/pfWXN+HU+l/ncC25wGD9bGJv+ve1T0/7pHrd5e/z/G02iQ0cXJv41/gfdzHIRLcHVm8RX9EA9Iu9lukdHwgoxOCWh4y+d/WBNwlFxQsgQkOrT8Jde+P1iRQ31QVpyL3HECvhqrNRo1Bf+Va1OfUeMMisXuxKURGBHwLGfUaJvNGpSbBoMpgkDQbEYMm9RNswH/zcA/a6hPGpsaEZ26LI6EfmOzOkIBd5Z7q9IyUN8ag1tHcsCF+8rNlnyp7IQdRBEqt6wRkmukFurQvwbtVCn/qR19mJmA3eP/Xr/V38f/j/FsGP/3EOFBFMbMOLx7LLBB//f7Uv+n499GDtjr/8d4bm8bz2unH0JU4qgBMQBQjipXcmbteePjx9rtrQFu6gSCcVLPeAbsBGh11IxYr06MrKSVeDExRST5BoGa7ywvAUcPS56D5xhB1Ez+JHGU+Dbpd/hPdz5KwL58IHWjTiQscBrxZ41jehxRVOFW2sIk8bwl+JCWh0bF4Z4+tmDWfqYCNi8fYwvYHwZ+tG2h/8kCQCoLW0TPAYbnCBfZc+euDAti9MqfjpecKidvRlgWTQYDB/qZWTub4KQHtZgkH0qS5YKnLWwQf8e9Xc/DGAcaBzyhEY68xHYrImP5PKHdSUpX9TGlrSyy8vs2tPdYCudb3o/Bd9sPboZjShEBxLwU5BJ1FZ65lzsiF0auH09I/R/M+AerF2CJRrdnteqfOQbURhYlRwVCFhOjK1lFlPKsMfW2HGFeIxveYrd0iovfMmSCLkUQRFo2wP1nndTf13cXLTEbxrFl22Erygp0ccoYnLAG78GA3N7KEHx9R02ByvqyjGLEGUSvZHOmxlmSDMM0eMRvUN+8TiXbdINGGqdDW+Uqf4ogtECWMhQIjcH5c4zxUgBSXDai0QL820qyjiTyOxG22GOjEh0xWbOJekJhmNU9ApmMLd+m+f7oYpnnERqh88516i79sbN6epc2oe7pA15GHgOQwId4YkC0BlbKbMm8aZ1h1I5oLKcmdu7TiNd+s0ozayVNW+CidKrUpRkAVLBFsX+6lkiZUTCfkfoNHc+C4NqIPfDoqK5LlNquaLMKUZZ9rtC3Clhd/gCVs0aLloZBJ31EJzSiwIM8IONfLcP1f+MCsPNQXNJJlfpslKwCC1FZrictfGIxjS4Dj75RFDY2dE3nMCb1gmXbQeLvxl6y7lBUXclb+WIF9lKjtAMDrYDrb80H2wDYzCA5ORWjQCA4obtJaHH4vnL6XdI4wYU8C0jmglo8444Io+CQYPUtfUwa27NjWf/75QhqZ3M2XMYJ4apLtKF01hS0p0J9KieDTGzatHw/iPn0CdNaNNMWtfK2FyROQwA2BEmL7Z2dYGt17UOEU96ZCuOlmPgsCsBo09+JoKCOtSxSBP8dMVPyGbkyY2CO6/SdRv6KPyL6e+JGQPmnXAmR+gSGEcYhIGlDqO6QQgNSX0E6jvIzDbeC8nmA+G9D/K9bhDuvB25c/zvq5ud/282j/n7971Geza6K8D2zVUIsYghPOOKudat27frAxZpzWJvT2HKs2BqAOGznpmpaVEiRr4x02TcVtpuXEi7iIBP2tfa87Iaa4Pz7gD7IF+kiSIzpEZzjM96UAG3siL/JFvbdKt7elrv6aeAp+2h6gW15AN1lLAFzSSeiz2JUz/hL/mK7gSw7TWKkModyCxjVvrWZN3ufW3a+hmd7/S+44y5WYOP6X6+w/tdut1v7+d9HeR5Q/0tN8eWrfka9ycid+uia3X7lCmeT/AtljqHXp/P/jjpi/a/bauP/QP5boAr28v8YT1H+M+O9Sv6jsWWbVhLPgsj9QyyLX79geU8wg3IHdbDKgdhJ3r1VQh4lnnDqDAK9+iEKkpANyC8YUv7KQUeUBUlkU/FWhuGsflgXDgz+oguMMVWFBY3GovBz8aoIGVGrhi4Sv+YcGjQAYTIFZch4K6SOM/qgsfif27bl0/gmiK4x+UqMSnXD8B1eMLo94Go4qabmCIeBUwFwSmPonOcy/N8N5gNXt2AHQeS4vs5S1Y1ya7At5nXLmYPrAjBzmRwSfhl8fZ7EPCFEzqSCWpy400RUY/UtOndYT0LgeFqJzcppjypUpCRs1SpvbHdTtb3+H4MUIVvtbgY26f9m76jo/3WO9v7fozxS/+Mi5hobsH629H4W4nvBVw/hNz6QhQCkZBCsRHdNn2oqUNaN3v1MHUvGuPohrZSAPspRXgvHN7ZRtZBgqsnP7Tztr9oD/ns/m/S/bv3uGgFsiv/7rXZB/7c6+/0fj/MU9n8oZYOe7hccycfLELexhNbvCa2Bzwf25UR2JGNzzs4D8idvNsfoA23RJw7+A8Uy46iX05rtK40K3ATeGVsDQpYghdqfZ/w3yH8WoNxjO9h6+W91mkdtFf93Oy2+/tPv7/d/Psqjyz+yQeainaRD/xdVBCsdOKw9c6czw1pYLpRyPTdeGkJyzTTAKi47C52B3hKN0qlAFYJzrNVifTsVZfVZrXCIrC2BP9/5+krr0BZdKme6lTSMkk3ZiDYy+GiL7eoV6LYZta9ZMs9b89wgylXqb80rCd78HobnAnfw1iucgPozjhqbWe1eHyBna+mik3xjlyJSGDhDLQegUFQpR62nL4pl0pV1fLwcSe9J1FxT2txJkTcCwwGKEgv3yFFnuxpA0gXuWJGFdq6ejIG37lo7Al/fnVOghStYOl9f8XflgLlza0ovQIKFH6ANWfHLYIehLA1kOTDZrFfWBjPA/kkczPFLPly6Cq4p8HscJTRt204i0ArHYPRws1NlPzL+HeWLV3dQJjmDNs3AGZm+1JN3NaZbg8sKfNhKZFrtPGQ+XANSx9b1sUW9FTAXZGIJFQalz7E1BaiFPO9cim292AoyxUUADCtTY3PwwvRjHj/qL/K9VeR6M3x9OroYHp/mvhKyQKj/ioL5oPCBiMz9dO264hsqs0GqMM3UIJXIrU2Hc/Tfce2BWe03QPbC4GU4n70e/nD67vT46vzy/fm708ufL8+uKvEfEJEkzd4HCmaDN6S94Fq2hFlOfCoRVopgFZI/DC9PTt+8Hx4fn45G76/Ofzp9U41ivbGwogZokYac9m4UdIz4s5EJqWWDUWVGjLJWX9f46PT05P3J+evh2Zv3ONArENC4KJ8VhbrLlBPYphPMQeYKHJlP6XIwY2y9t7I+581cQfSsgfXU5h0+H769+rH9/uLy/N//eX/86uz0zdX7s5PqvkPXV8Jewwel1xBoMF0eDFI3jD+s0HDognrfoT6sV332gqnh8SLt0nfhDHzXAJI1CrFUqWzCqKEvF3+njWllUnQJgkpnxtLMcNxINCxfryyO5P9uNx91JSzcK6ojLk2QyfeQ/knQbcrXrtIhldZUFebG9ynq8A+razWf5StyHOWSxtIQQsrRlJmiRYxKzFH50nMXIGiMXUTBmOZVKZ5/8AONi/o15Gq1MaOWF8/+KH4McC/Ii+aLVuEDA58UJeTHq6uL3CfXd2PX8k6oZ4EcAoM54Pn0m7kyIY1cbpPF15b+FTjJce/UA6y5/EQd6NXyIFm12ZMsV2gq9SsuArmzZi0rFnsQBXFgB96AXB1f5AilFpo2+RtpyTWexiLwkjl9jc5WqW/cIRPWVxfeAp6CAlzON9QvaJ1qOHrIUhy6ZCygrQN0D0cg1TAGr7XgtYzUtBew0XtXcgsKZZFF8ZCknCub4Xt/96Damq/B+D5Ownr8S1GJHzg03UyVFtPf3isaKbWHBx2ALGsuq3rzsO3EgUejYmysvbxXa3EQBmDNl6MQeQciBlwAd3NCCgJmfRhd0xvQpNqQqJo/UWC3/L6rWcBivqEgK40nhr31GWDMJi4euTAgI9CQTuLRob+8sZa6jcE4vDxmnLXKcyZ65+8c5re6GUmEqqqI0fK6Z6s9XBl68iww6uTxrtSx2KQQmKpgZcuVwzUZsnoX1GaTDD6dh/HyxC1SnjpuMh+Q13QOUeHq2ReNXCtUbFXPdsn9LU0dVo7HJoW8uzIW/XlthXnU7zLfuYXil8H1a1BfA9JtN9dRfAslvrUC3zQ6GwA87OaT/fPZnw3rPxojf7r8z3L+T6vZ3J//9CjPwSc8/umgdrDd4U+GYRT3Za7S75Xr1cdKdd97pWql5t59/equ+/Ur7N+u+/YVBSpnFXHFuzhDWyQ0xpLZetpe6X+9zwb9HwaO47Io4cd+jhNnSu+QCLAp/6fXKe3/6e3zPx/n0fVpyJdosgyAi8A5SQf/ez74X1oqgFrnhBD3rS/TATA4xUj30y/Xf+7B3eLZIP/pBDNECNx4Wx7bWQFskv9Ov5j/1+539/k/j/IU3C4nsK9pJPyp/2XqNKVdUgQzhgLeQa7ZUuJF+k3eyxHYiMD8N8AmdWzM4pfctHhVJ/YpzNXPBvnHBVe5uPQJ4792p3j+Q/+ou5f/x3jWzC3dVe4LE0efKQUYAa3M9QuTKAwYYMSRNPCwFsrwuKm1tWzPYmxAxNtaRbKdXI+Txz2tTjWUE6jAesHcqDxsfxdoknTkya12vE4R9RR0fVDn6/4fn0iVey6ypPcK8m/5bNT/YoX5XneBbNL/vV6rqP9bnaO9/n+MZ4WS56P+pQV7FRpZy5FdqT8nEWhhKOU5Bqbd8vQM8uSX27pKnQCVeXV8UT+s47f64Pa2Kv/i48ePvz7Zus2ULIaKIWWbWhgKLdUL54/qyYuAlQBa36nlMHAMTsG0ZSNDxvJczHV/ku1SRsClJWvVb6uY1g1DXLFA3S2dkabCcmGBKjJa8IOopaXLGDIdZ8sMGLHPRiTN5HNOqnJiihk4+dmBe00FdP/CM6fb6X/lg9zNDGzc/9ct6v9Wr7Xf//coz1bHYRY3eBcNhdqVvLu9WJPP/7iWY5WOU5QoqbqSqVmRnVNWfltsUni8FZcN8r8IrfvfA7fJ/+u0ive/HbX7+/XfR3kK8o/jLe7McQoyX0e2ZTZ4COnRMo1Fqy4VwTuMyOHjReAMZbm/7FFgGxcLhOOQ7iWp2iKJ70vbJO+aLgQVxYkxcgMNByTeiPwgzeHBAdILm1m5FYoMa8xdfyh2f4lCyjvUG9TSjOGlmyWtGdmnNIPr2xW7mVIl4lxW5RcDqDDJ/T3P55tliA5WOJOtZkmh7ten7/5s0P/SH/6k8X+70xTrP51uGzw/cf9PZ6//H+XJKbc1J2Vlq8Kv5flYPwvWOM6lgf5lDvGpcNBWhsTiWmAwcdmGqK2zf4unYYqLCwzbMnBaYac8Xn51QZrzoyk1KYTyPKA7pTXhyWyFbgv0+S4zMYZKUUvPN9Pbd85bUpU3G3AZl4tNBRw6P4aNGosW4p6V2GUCwLa+T3zHkz1JD/4ThicI0wR7PFHt+PJ0eHWKh9i9vTjBX/J0OekAVByEl3cNxDdwiLSv+VPr9MPxSkZa6dmAn/xU3OaQf7s23OhX8M/aFtPxKTZa+nCndpnr0NPJhB9nRd4EPj33T6LlZSJSilONc0kXLr1JaZmOknS1Iur6i0DcLqt2GZ9N3lDqUOdza9Av+6m0/wvBIg91Afh6+9/qgOEv3P/I/7e3/4/wHEAAI7b5i0Hnt1JUqfdaTZwmwKMHdXrAgNAkAk1qiJQLM7yemg5dpNvADLktpiHvx8s2iDWyKebGihXQUDtSAIQ9iC9AoYo464CoS+bERdscNYLHFtzMAkbTowtyV5BnF0ybPMibinumW2anLjunn2xBfvmV34auGoLC9VrxDj3+spbRMD0PRtz3oy40quogyY5WqmWnzLRrtfzE04D3dgSRKeZNM9xoBRAjYpUuF8ouURceChpN8SvdLnhA9INY4gD0r6PuCi+AKzhQeA421r/a6oYjk5c9m/BrxhkVF7RLvwmHBLA5hB5wQPC3upnXEbeGc8CK0ul5N6lDiRTXvKbVBMrd71UkDr+VMO+7ISqhYDHwI/Srh3gTP8+oTyaWxwD3lYMqoLNDEiHpAB3suQjRBStKs6sjx0xtpHgDlaReeV3ZLtRO71aCD1JIaMoCKc25o1A3yneJMX6FYC23ZQhGIzvFcs1o6Lc4bcWrJQKU74H6lIxWq+UPLuIyUCsfBsPfH5AJkyeFtsGmoRRXFbKtUBxHxadXDsCzcUB9il8GGb56Bb/UJt9LMDi4LYMtoddzSRf4nPhDBo4Ufs6/fMtwX0VLNp/68GKNTZ5OenZRU050q9nuNSvEvJbbGc5vQZUOmR0mvHtzkTDLZ27gRa//2uVWgSfR6GVbxbL9LhStLUIeH8p5xozntcmfTTA2zZjVcRYSFEVuezD2Tt9Yiyo+3dPLuy45HuEVfG6hAIEx8i4xrwXW6OzkmAxBF5BTZdZIPjA+UCNg3ODVqKn149sOa6XTByXIiyhYQPEoDwzP3YrELaOW56kTB6t0FpBTXWlrWz7Km9oLAs3z+tg+ijKVYLDneMxtG5r+IAkrkRnZYOmFU4+/gMjwr+86hM4tVx7+IYuKsJKcnRRQFaBx/fUDaoc8xodYGArxS9hZGPipYgIti/YxVvTKKCEhoC5GqJxYWmB75nB7UcZMKtDPhd0BAWFl5OKn41OFEbaNCdYSEG6oVlpN65DwToqdgj64/N76t5evPmOfRnijMkdIfWBgMUIemt+4nmOD78f4KRxs0Gg8N/FIPX58j5xFbghkGzbgNLbsaxn6ib69jbxit1UrBL5lZJV3K4Mlx9tuoT8Q6nqece0HN35DcKyR75LjAkODXCz5BISIuKF74j4TvV3GvDOfa3Y6unbRm3Qny0x/4eEf4us5VMcSAgQvJ6mZlcbUjkvoZk7Q8KWQ9fQiYXxl4PHT6Ex/WGKPpIUbiXOihzzfUkTQRB1RjebN9e2A31OtVLNsZEjEkagwkFZ2LfXcipAbhDugrhC0544p8VHjhj7+NOBuvpwalBf2TYNGHAQea6RVG1boNhatAwFBLJqkHRzFkTagQ+0eUN6+lFC59IDYYlXJjKlnjfd3G5ffD7mqBOJUkIRlmo17FZhZAgxPFy1TSNNl2rDq4hT8n2RsAvUaWQIO78zYC8YNCBraL0zgU4AC3eMnRzKgycGrVrPVTbuZQkcrgW4Kn2bknqc2zJnTKRFEb8YVXhN3fDCe4YU4s4tb2os8kTDpXoqugoV3nrCSS5+SGrwGhl7Q8ZCM+QwZSnVI50jWObAEZz0YhQVn8NTRB4xcvgkkXiJqKIOpsBwP5VybPqRyDLk7aVumDXrgmi6z5SSBchGZRx0ogfuaodI7Vxqsk4RzawU648jy7T8ahYFq8Eu0WKPdeyluW+OMDJqJUDc/4vENj0csEEsf3Bo8qS/g+7BqwrA7eEu947j4yvLkpLnS3hkXpF4ty2bWVSxXhGHlY8M1gAou471gCT9fHuNW6dhAocxMgFuunbAMlQVUeRyJnB1XHJR9y076k4yFCxXAWK/0s0jWqDhgqbllz5Bpl/gZXzCej4f6LQdl3eRpipO8PPvxEKo4dEVQHtxfS5EaXGiwDNSa8xDhkARcG8+oMiCcIzM/BU0tuAzK5FDH5HC1vLvN7chMPPIUu3rI+/tM1To/OR8Id6Xo/QJzKMcCmQ5NWapFWGoc0lZAIOeJLy2wjqPKA8wPjjxbEAIU3PkWBq4Ud/lezU6rgPUgs/8aEHTFhA9yyE020BJK+/yCYyEQGVMfoqJBZ6+ox29vkZE+fjTED3l5o2wKj+G54C2kSldrH7+mlFA9gmYcdwJalODqFP90e5vB+fiR/BNeZIjl2hoUm1BQdWEvtljY05CNqxo/f+r6H9LjHPP5rugEUt8xsnzNOp63NqqjiyenLzh1gTchlnTZTEiMorDwJ6WNxJUI8EAlGuXJLYncq5Hc48K7AmTCaIEB59JoLi8nkoVjj2V2IwVwHkoVKIeQO8r5E5TTsmdxGo/JcVdzHDxIvL3N1dMPmtWjRYgtz8BLtxifKVFHMRzyu4UZmQPAtAaFuMK1Z1p8BpQCr0oYfN4+/4DMZta44HLnQsQEKcm4Ff/vjnc5/xfgQVQTCWB8tlnNz3rBFJOHCrM9WNOsyQudhbZXq5/Qagv+fLWmHhbXw8BWs9PvTV7YhvNybBnd7uSl8YK+6BlH3RZ9YdvN1uSlDVXSYzeFlhnTLNqRtIGANyUnKL+4MhzKodouIEMG5OULq9Mf918a/d7LttHtdyxj3G/2DKdr9/qdyYtxs9XfJ7Psn/2zfz7p8//ckQtWAKAAAA==
  values:
    replicas: 1
    clients:
      - name: local
        clientId: local
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller
      tag: latest
    imagePullPolicy: Always
    webhook:
      namespaceSelector:
        matchExpressions:
          - {key: "shoot.gardener.cloud/no-cleanup", operator: "NotIn", values: ["true"]}
          - {key: "gardener.cloud/purpose", operator: "NotIn", values: ["kube-system"]}
          - {key: "kubernetes.io/metadata.name", operator: "NotIn", values: ["kube-system"]}
          - {key: "gardener.cloud/role", operator: "NotIn", values: ["extension"]}
      # TODO: Add the moment there is no single label key to identify the components which should be
      # enahnaced by the webhook. This setup is not recommended in production environments.
      # For production environments, there shall be a single key on pod level and each component
      # shall have it own value
      # objectSelector:
      #   matchExpressions:
      #     - {key: "gardener.cloud/role", operator: "In", values: ["plutono", "prometheus", ...]}
    vpa:
      enabled: true
    configuration:
      oauth2Proxy:
        sslInsecureSkipVerify: true
        insecureOidcSkipIssuerVerification: false
        oidcIssuerUrl: "https://dexidp:5556"
        scope: "openid email groups"
      kubeRbacProxy:
        oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVUnhGbEtnWGgzQWROYThhRHBadCs1MXdUSE5Zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd016RWVNQndHQTFVRUNoTVZaRzlqYTJWeU9uQnliM1pwWkdWeUxXeHZZMkZzTVJFd0R3WURWUVFERXdoTQpiMk5oYkNCRFFUQWVGdzB5TkRBeU1UWXlNVE0wTURCYUZ3MHlPVEF5TVRReU1UTTBNREJhTURNeEhqQWNCZ05WCkJBb1RGV1J2WTJ0bGNqcHdjbTkyYVdSbGNpMXNiMk5oYkRFUk1BOEdBMVVFQXhNSVRHOWpZV3dnUTBFd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEaUNRZ001Mk51dko4a1p2aUU5M0JHN3ZobgpjNzV3bkVMdDlEWE5SWkhwa0xqSHFWV2xuaDV1T1k1d0FNS2pYY0N5NG1NZFFHdHVseVZBOFIyR2NTTFhlcmxYCnM0Z2hwSklyMTNMZ0RMY2UwSVc0WHlMdDVYVjFKRisxWDdJY3hicXZCTTcxMXVEb3FlNG9abGRFYVZCSXlxdWcKZS9GVFk5c2h5dHhHaEViWGErUU5KWWtEaDE4enhuR2JsVDhMSVhqd05qQVBEZTM5YVNwaW1JVkd0M0lLSkhHeQp2RmprSGM2RFlMYm9GV1hMekd4a1lqVUVDZFFsWkdaeVJHQ1ZIM3JCQVFyd2VJS005REVvbVppWW9jSlEzM24wCjZ6S25jaEdhZXlYNnZITk9yNVhnQzk1WXVmWlJMNmhlTWxTN01qMkNyL1R0bXgvMkgvNDZFcGM2NzRDakFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlRWUC96NTQ4WmlGK1o0emZrQVh4ODVlMkJ2bURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxRUllibWJYCnZHNkJCMUVDS0xpNHpoNitmeU93cG9TTDRIWW14ZE5aRjVVV1ZFencraS9JY1hJOVVDUTYxYVhjU3hPTE1vN3YKOG5nYkg0SE9CdFZ5dVdrRWN4Yit1SjBYU1ZDVDlZd2J6ZUFocXhoaGNJTzBobUFJYlhGRWRKQ3FiWHhndUplSQpEUjVKMnlTM24rbGxRY0NVeCtiWUR5YVdTOE9lamhTbTlIbHl5WUpHN1hjd2VBMkV6S3cxU2kvQjkvLzV3NlBRCmFuUng2WFlYMG9lUk1rZ245NkMwQU81TFNza2pxUnBBeEdtbnZiS2wzSklIcC9wQVpybStuN3Z4aVhvQjcvdi8KblFKbXExQ1NxamJmNWd4TGJUR0svcVR6TzlqLzJHL3FxRkhuVFZSR1NETWoxclhMT0ppdFpoOHdWNzBzc1ZJZQpyRGhKWWRNejEzZjdMQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          hostPrefix: pl
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          hostPrefix: pr
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden-plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden-seed-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: seed-prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden-aggregate-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: aggregate-prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden-prometheus-cache"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: cache
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
