---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1dW3PbRrLOM3/FHGi3YmcFUKRIymZVHhRJm+jEtlSi7OzW1pYXBIYkIhBAMABlRvH57ad7LsDgwptky4oXUymHAmZ6enp6vu6eG0LPdUw7ipjphEESh75P4/Y3nzYdQDrq9/n/IZX/z393ev1Bf9DpdjFf53DQPfqG9D8xH7UpZYkdE/JNHIbJunyb3v9JU1jX/9aM+nNvGoQx/RR1YAcPer2V/d/v9Xn/H/S7hz183ukf9TvfkINPUfmm9F/e/3vk0k4SGgeMJCERfU5uZzQg49TzXS+Yksh2buwpZVZrj1zPPEZYGkVhnMAP0BOfTP1wTOZ24swg9z6JqW8n3oJCuWSmPbcDFwgEdApvw4A8i2I68T5Ql9x6kO9/nlvkIvCXJAx4SWSJRDQmvhdQq2Wdjt6PEuANSJyE8zkQeHcyIq4Xs5Y19ZI2/1ew37LGv8dt/q96MJu28R/1J1sE7ZzQGNqXRmTi+ZS1vrPYbQT/ju0b+DeZ4+8Q6LS++z8o8c6OvTBl5Pz0DOqN4vBX6iQty3Op3RbZ4VHLWjAndGm7NfaCFmN+60t38ppUO/5PZnacWEt77n+SOjaM/0738Kg8/vu9w2b8P0ayI+8djRmMyCFZdFqBPadDUqcULZcyJ/aihGc9Jj+BiSAOKgqZhDH5OR3DiKUJDCEFE/BfMqMyz0JUYolX8i8SpHMoBjgSpr5LxpR4gRPTOQ0SwAVqOzOSeHNKlmEKQHLDaQWARFADgFVOHKCFeIBHCZ1HAD6U7SMhP+XwhdmgLRkHOIzFT0ZsADv6IYJBDPUByQk0NbwlIzq3g8RzVEYk82yWJBEbttuMzoEUgMK0/by1ULI7sA6sTrnppWaGE8WM7zkCBccUabs08sMldTdIB6hvJx8lHa0mq9joIEz0hgPl1U1HruhSsQGo7UOxQvvKrYI2pAxLAt3zBP+MqQNgSwNXyDll0NWJQP7f0jBB4wIEMk00FlyexlNGzq8j1eK/GzrWNPxkdWzy/3pHZf+vd9TpN/j/GKndJqPL03+Yfwfv5ySMluDqzJJr+iEZku5Bt0NGx5dkdEYA4e2A/2FPwFHyAGQJjOjIDpYcfX+0Y5cGAFZci7xxCr4aa7XbLUX/lefQgFHzHLIl3sSjMRgR8Cxn1OxaBy3INw2HUySBpNmMmA4xLKsN/83AP2urV5qamjGdeiyJBb6xmYFUwJ3l3qq0DDSwx+DWkQJx4b5ysyUfKjvhhHGM4JZXQgqVtCKd+teATrXjP7Ojn2YmYIf4H2CC+3+Dbr+J/x8jbej/9xDhQRTGrCS6fyywAf+POgf9rP8PD7vfHHRBA7oN/j9G2lsH/72Hwf9ea28r8DdNs3V31/6udfYhQmqIxBiIKIeZg63V+q798SPkM8FdnngBJUauu8AwVIAIjeUMYuY57dRPiCUi2jdI1Hpn+yk4nJjzAjzYGKJ38gdJ4jRwyOCQ//TmoxQa+oEYpkEkLXBe8afg9CSmKAM7q2GS+v4SfFnbx/a5POLAGqzWL1TQ5vkTrAHbw8Cfd2z0g1kITOXhk2g50PBd4ar73tyT4UmC0cGz8ZJL5fTNCPOi6WLgyD+3WucTnHyhNpPiw86wPfD4hS3kz7jX7fsYa0HlwCdUwpmX3G4lZMxfFLQ3yeSqXmaylVlWvt9G9j7L6PyFt2P4/fadm/OYSUQQsa6EuERZxWfh4Y7MRbEXJBNi/JWZf2VGiZaodHtVq/9ZUECtZ3HkqIDMZqJ3paqIXL49pv6WPcxL5N1bbpYucfFbhm7QpBiCWdsBun8ziPHe2H1oiVk5zi3bjluRV7CLU9fgDLZ5C4bk7k5OBaxvqCVYWZ+XUYx8w/iVrM7SNEuK4TgLYvEdlLduspFteWE7my+AuqpF/hDBcEksVSoQooMT6prjpSCktGxE4wVAba1YR5L5nQRbbrFZy46YNNokPQEYVn2LYEwmduDQYnv0YVnUERqjHeGYukt7nLyc3qRNrPt6h1eZR0sYBmDahkSrYOWYrZg3rTGMOjFN5BTJzm0a8dJvViGzltNyBC8KUyWW5gQQYMvD/tlaIeVGwXpOjFs6noXhjZn44FlSHUsUbNfUWccoy1/X4K0iZsgfADlrULTSDbroYzqhMQUd5IEhf2ubXvArHwA7d8UVndTBZ7tiFViEYLletPCKJTS+Cn36RknY3NA0XcOYxAXbccI02E29ZNljUXSlbhWzldRL9dIOCrSCbrC1HmxDYLOCFMap6AUCQRLdbYSWu+8rl98VTVJcULRBZB7A4jl3RBgFhwSLb+lj0sSZncjyPyxHUDoPH/gYJ4RDl6hDYdYU0FOxPpVRiYVVW3YQhAmfxmFajVZWo5bf8cPUbQvCphBpub7zU6zN0F7EOPWeQxjPxcRrkQF6m/5GhAR1rmWWMvnviZWJzyzkGYNy3GTPNPHX/BHT31IvBsk/4yBEjAl0I/RDSLKKEO5QQkNirBAdZ/m5xlsJfL50ENuke6cN8z+6Jb73evCm9d/+QS+f/+n2cP7n6KjXzP88Rno68z+bXFURe+Sr1ZjFFJFQzEOrTuvGCwDFtOCgNaeJ7dqJPQQ43C5M0ayoQNFAOWnV2ET4bjyXCBGGOdiv9eeqYYgFwV8A7IOASA9J4pwOknMDxqsSpM0d+bfYwrlfwbu7alM/Dz3lH1l+6Ng+UPcYS8FdohPRZtGr5/whf7BdR1adZtFTeUCxBY362Moquj1fegw/JG2P/6JX7mMFNq3/Dgba/D/m63a7vYMG/x8jfYX4L5Hizw/9jPqTkTcN0DW/+0yAs2n8CxDFkPez+X/dTi9f/z3sw/Nu56DZ//s46amO/9x4rxr/8dh2LDtNZmHs/S62Z9y8YEVPMKdyDzhY5UDsNN79VYM8Tn3h1JkEWvVjHKYRG5J/4ZTCvznpmLIwjR0qnsppGGbsG8KBwV90gXMMqsCCxmOR+TvxqEwZWaunLjYgzjk1qCABeQMYMl4LMXBFBxCL/7ltXQFNbsP4BjcBil6prxjewwNGtydcTydDas5wFLo1BKc0gcb5HsP/3eK+9PoanDCMXS/QVaq+Um4NtuXcsN05uFBAs7CjSNKvkjfmacI3JsmZdBhZE2+aimLM2KJx+0YagcbTWm5WTnvVsSJHwla18sq+Dt/4vyFtb//HgF44nHd3Azbu/x8cafaf+/+9bmP/HyU9MfuPxNb4AOtXSx7mIfwg9PtTxA2fyEMApuQkiILuNW1qqYkS3el5mKvD0jGufkovRVAfFSSvTcdsrKNuIdFSix/bRVqNWfnkaRP+617HfSPATfgPeJ/j/4DHf2gGGvx/hPRU8L90Dk2BDUY6f+KZnGQZ4XG6yP4tpS3w+cG+nMqG5MOND6sh+YNXWxhwQ23RNwn/Cdly46jn06odKEQFrQbvnK0hIXOQUukvrZFNesy0Af/ziYEHHAdej/+A9Yc6/vf5+u9Bc/73UdJTxH9Ux9xFP81U8IkagpUOPJaegUBNe2F7kAsElyxNgdxWNsFS3nYkbAZ6yzTOlgLUFBznWm3W6mZQrl6rFU6xa1fwz29geKU1aIsmVXc6VyyMwghZidYzmLTNVuoR2LYZdW5YOi96lYVOlLuU/mJdS/LWD9A9l3iThFHjjBrPOWtsZnf7A6Cc76USjeQHjJWQotA91vaAlbIq46i19EU5T7azCpNfEOkDhVqoSps7LetGaLogUWLjWW3qblcCRLrAk5My087F0zHo1n1LxxDreXMKsvCEShfLK/2u7TBvbk/pJYxg4QdqXVZ+M9yhKysdWQ1MN+PK2mAW1B8AcI5viuHydXhDQd+TOKVZ3U4aAyqcAG4i6ta2I9ffUTH76gaWplJABUJezrcZq3+a7ewURArvMpmsKamdXVghZ3n4BlA+b6aZ47h+qEQbDGtktEJObKWQOt0iZa5GQ2JoLeOPEE9D5sFYXUKBYeV1Yk+Baun8UeHoh1GuBZX1MoSBtCwIUtCLspdF/miwKLZWievN8euz0eXxyVnhLSELpPr3OJwPSy+IOFGW7ampeYcgO8yA3MoMZUXc2jIdZ/8dRzU8bXULYi91Xs7z+evjH8/enZ1cX1y9v3h3dvXL1fl1Lf9DIg7vsPehotnmFWkPOPpXOCuoWy3DCqBWMfnj8dXp2Zv3xycnZ6PR++uLn8/e1LNotBd23AZ0a8vluHYJ+8Sf7Rw8bAeMPTMTxABjXeWjs7PT96cXr4/P37zHjl7BgKZFxd26iKmWXFiz3HAOY66kkcWtxi7uZF7vRa3fi22tEHpewXpp8wZfHL+9/qn7/vLq4h//fH/y6vzszfX789P6tkPTV9JeoweVxxAAM308mMQwzd/tyHTpgvrfI04bda/9cGr6PEu38l44Kd+3QWTtUoxfyZuCT6xvY/le69PawzoVCuqYDeZmpuvFomL5eGV2FP/3u/nOK2nhXQo649I0WvyOhT8IunPF0nUYUmvlVWbuFDxDDP+wutTB82JBzqNcal2aYpByNqWdK3NUUY7ah763gIHG2GUcjmkRSvF+oB9pUsbXiMNqe0ZtP5n9Xn4Z4hnFFwcvOqUXDHxlHCE/XV9fFl55gZd4tn9KfRvGISiYCx7Z4KCQJ6Jgnt3sbUd/C5rkevdqAZZcfqYG9FtFkqze7EmVK1WV+RWXoTzxuVYVyy2IwyR0Qn9Irk8uC4JSC+Cb/I0s5xpPYxH66Zy+Riew0jbuKArrqw/eEp9CAnycbyhfQp16OnooVe66dCyorSP0AEcgQxiTl1rwUmZm2kvc6K2ruAWlvKiieIlgwcXO+X24e1Bvzddw/BAnYT3/lWgpCF2aHfLNsulPHxQlVerDmSAYy5rLqp582nqS0KdxOWbXHj6otiSMQrDmy1GEugMRA27M8QqDFAaY/WF0Q28BSbUuUSV/pqBuxfPAs5Al/KBbnhtv1HwbMOCYTTy8kmhIRoCQburT42B5ay91G4PzA9U+46pVncvRG3/v6YdOLxeJgKqaGK2IPVudLc7Zk3dlUrfIdy3GYpViwNQFK1uuaK/Zua83QR2CzOnTeZQsT72y5KnrpfMheU3nEBWunhXSxLUCYutatsuZhMqUZm1/bALk3cFYtOe1HRVZv8887BbAL4Pr1wBfQ9LrHqyT+BYgvjWAb+qdDQT+dIciN6z/aB31+c7/HfQH+frPUYfv/+426z+Pktau/zzw+r8H7P9eBV+12wROFDI9eIFoJTDtvmx032tSauB91+tSlARqJ81wo0F5ArIsaAyV8mWsPx2mNWn7tAH/o9B1PRan/NrncepO6T02Amw6/3fU09b/j3D9vzto9v8+TnqK6/8RXwrJdwBchu5ppoQ/cCV89K0AD9gGoNY4IYx8G8itABgAYjT5CEv16/t/0/iXC30OX+j7TPs/O33t/teDAfp/vc5RM/4fIz2V8X/PRet8qkEHECamVvLDZxqW6MXrUWTT8viWXp5+FeV9Pbl8vSu7x8eoZ4/nFDfti4zGinaIjEAbP9uC8/A8zh6Sie0zWvzIg6GERfjwz+5Fy3o7Q6G6BltG4zk+/bQB/7MFNBhofPCCluxsBjb5f/2j3P/rdQ65/zdo7n94lPTE8F9hiBs6NzQWgf3/MnWb6i5HBHLFBh1G7d3S4xPbL4sgLbgRE6C/AjdZhG2V3xSAsK4RT+0I04bxjxtK5OL555v/6x4e5uO/e8D3f3ea+O9R0hMd//oc/n3HfWmC/gsdAUJCK/d6R2kchQw44kya6LtRhtfNri3FvbEhEU9bNZut5b4Hed3r6q3mcqEKhkA4N2s/+rULNRUpf3unXa9ZZj0jbQwNvr/q47cSci/EKamnBpBfedqI/2IHzYO+BbgJ/48GHQ3/+f2Pncb/e5z0VPB/Bchz7fvznfupILJ2RmIlfk5iQGHI5bsmHrvg2+DIt/+6M9QWNYDM65NLY9/Ad8bw7q5un9vHjx///e3WdWZiMdU8oqxTm4qEmozS9wf0TeLAlSBq7FRzFLoml2BWs5kzY4OKISP5LTVIuLI1SLXbLh/rgS6u2QjUq9yRrKZmhQWq2TmIL0QpbVuiKbc9brnTUJyzFZsTi3v76vYelnc6FmeIHzQd3KuZiNkO/5Xtv58Z2Lz+r+P/Ec7/9g8b/H+U9FTwf6vr8MsXvJQNhbqVZHd7seY81+NajlUYpyRRgbqKqVmxC7IKflscUmsmcL/2tAH/F5H98O+Ab/T/e/n+r94h5OscHXaa7/89Snqi+I96J77d6pYw30DYYo5dXN0zpCF4hzMy8PIydI9lvid7FfDGDQPCcczObNZdkYDPK9ck3Hdbbp35wY4Q10jqB1T1J8Otve18SkuWbMl9xer4Djz08s3gZv4q2xn9lxWnhDPwcq/qzu0AqSgt/D2v7uOutHvuBcfirLpeVf50Vcs7B2svDlhVm/2hrrbs6c61bWW8N+C/jEM+6/xPt9/pFr//28UvgDf4/xjpqeB/AdzW3JSb7+R4Le/H/UWo6EnhuMWTucSxxkFfOSXiTYMwxqPd+cHjrU/ZlG/DFx+uMx3bxGmlnc7L8E/XZZuPNRSRYCDvg7zX/mq8mbnUbME+P80t+lABt4x8chy/9wZqVXizAZfzMuLwHqfOr2Gm5qKDvOc5dpkAcuwf0sD1ZUuyi7+FIQqj7CAb3qh8cnV2fH2Gl1i/vTzFX/J2aekA1FyELd/I0SPegUOkvS3eWq1fjl0xRArvQ37zZ/k4YfHp2nBzUKM/a2vM+qdcaeXFveplnkvPJhN+nSl5Ewb0IjiNl1epOLqTIc4VXXj0NpNl1kvS1YqpFyxCh/eX8n7OJ28odan7pZH8fqnW/i9E1zw48JNpvf3v9Lq9bP2/2+33v8HVn86gsf+PkfaI3AEo7tYQm/zqYLXVErflcC9e3Y4zJDSNAcFMsdXFim6mlksX2TFnUx77bMvvkucHoNv51H57xcpzpF2ZA4MsTC4ByER8s0fUx70Z35HIWSN4Lc/tLGQ0u5rHY9r3r+3sgh6LB1dTsLSLA6tjHRqycfqNUuRf/24h9KiKILPRKn+7nD9s5TLM7mET31lVGybrGkjyqxVb+e1u3VarOOE35K0dQUSIfhPDg8RAEdyxykdd2SxMfRc/7C48AzRW4ld2HH6P6BegJSHgnvyufOUbsSXHBb8/g+Wvt/qyrMXznk8IEIAsCfcRpb+CXQLc7EMLOCH4e4oKgRxDWfycPRJWks7umcscOZS45q2sFlDhu8pl4fCvwRd9JmQlEioG9lv/5Cuv4pcZDcQu2f3VnSqos30So+iAHWy5iJaFKkpzpzPHLK2nxDbcOlGv/Ez0LtLOvmkLL+QgoZkKZDLnBtowq99wZvzT7a3CkVjojfz28DW9oX89dytdrQig+v3dz6lorVbxwkA+BlrVS9j48z0yYfKG9i7YNBzFdZkcOxLXQPJpjj3wKFyAT/HLJMevXsEvdYnFFRgcDMvYElo9l3KB12lwzMCBwdfFh28ZxlUdWX3mO4u1TXkr/PllSzmvHQi8D2qGeatw84nvzT217ulEKW/eXBxW4TMo8KA/eO1xq8A3L+l5O+W8ne4LyNsq7EgXKlPVf7n3HWjwP8u7uzRT0VpEPNCTE4Y6kcJEFX+iJq/EyXIDZwkN+QJ8PyfhTiDfQs8/h6MKYf8Uv4kSpeili5bxD6PsSXcbrE0wpRqRIbnmM3k/QXBN42t4fSVlxUtpE0qSChden8tuT5PeoMcFvadPCuklZNfsVTqnVbgFBDtZvz8DLV12dQfXADnwkXjJ5Rd2APqi6JHzUmCUz09PILCPGDlT1p0U4/I9pYjmLZjP/AABv12gVbn8WpK8jMMFZI+LxPDaTzwRMV7ilZLqwus66AZhiTvuwDDbAcKOOhML1fPyWD8iGpVksOX4lYUuVP1BTlRKZkYOODwipsBfoEPwb+C5hM5tT97xJbOKqJacn5ZYFaRx+f8DgmSR433MDJmcMAaFi8Igw2fQe3QTEiWvXBKSAo4OpMqFpcXV5y43m1XOpB35UtztEcAsRi5/PjlTHGHdOEkkCeG9KQrctQYJJ63cKGgDjDgnIW+vXn3BNo1CsCacIfWCgeGM+MzAree7DrjAjF+2xYbt9ncW3ujLb+mTk9ptwWzbAZ7GtnMjI0/RtrexX262qoXAu1ysLrHxC+zg0IDFxvZApO375k0Q3gZtobFmsUmuBwoN42LJ5z9EwA/NE59T1OtlzD8PuIGjoxsPnWpvssxRF+/4Em8voDjmECR4PinNPDfuLLqCZhYGGj4UYx2tPO9FfGTi108wpviwxBZJQz8Snyk55tt9RQBP1BdS0Mp7gRPO8Uecoy5HBSJu5IeOtHnP+IgMcztGbRBekfqCvTN3LcmP6jcMdaYhj3bkzKT8Xvw0bCdh6LN2VrRtR1570dkTFMSaTdbAURJrHXoMTE5oTAOHivrlCJUrIcgtFpXKmAUYP6Nwrn445lAJwqkRCcuRjTtXuLEJFJ4uOpYYTVdZxaqJU3AD07EF0mvn+794Y8Z+OG5D7NR9YYGeAhVoHr+4moFM9l51IKjPmplRRyuB3hqf5eQOuNbNue8tGUSnzhPOI/f/MKzjmbiyu7zZZZ1ImfSyRVPB0XG/ZZXIJhM1OE8MncGTYzLmE3Q4qiM6R7HOQSW46kEvLLiCZ/EOcOTxiexkiazhGMwGy8mxnOrTu1T2IfeqHdtyAAdu6DJf3RIsl5l51I4SvK/pKr1xlc46Tbm21rAzju3A+b1d6qg2/5Ywa3f7L8XHnrkiAzIR6hV7PLnlYZkNwzIArw0v5A356cSWMOwuICkEsR4+sn05Z6/QO9eCzLlnLe1E98daGnYxRF5DqOQ5P4iWCHfkba21jg1kys0ERCfaBz72pINJ5K1jcnJeaVD+Lr/QVyoWrpOAYr3SrxxbA3GgUnPbmaHSLvE1PmB8OyjiW4HKurnbjCfRFY/IUM3dakLy4P7aStQQIYBloPacR0r7JORoDJmkAeEamfspaGrBZVAmh7oWp6tt+9xcj9wISp5hU/d5e5+rUhenF0PhrpS9X1AO5Vig0qEpy1AkP66b1QIDcp4G0gLrPKptqMXOkVcIQ1iFB0Cj0JPDXT5Xk+MqctvL7b9GBF0x4YPsc5MNsoTcAdptOSBypd5HoEFnr4zjd3eoSB8/muKH/Ha8rApv27vkNWSgq9WPbzNJqBZBNa43ARQluDjGX93d5XQ+fiR/gwc5Y4W6huUqFFV9sJdrLB2pyftV9V8w9YIP2a3Nxe3W6ATSwDXz7cIGXqs6MtDFk7M4XLqgmxABe2wmRoySsPAnpY3EhRDwQCUb1Tk+ydyrkTxixZsCYsJogYHm0nguv40qMyc+y+1GRuAikhAou5A7ysUPOGR5z5MsHpP9rqZ6eJB4d1cop98nr0eLEFueg5duMz5hpFakwbenFEB5DgSzEhTiCs+ZafEZSAq8KmHwef38BSqb1eIDlzsXIibIRMat+H/ys04rv6mqXEOk9x+gB1FNLIhlx/bxDz+c4t6l0qQXlrRa4v8S7dXiK9TagT9frSknpweyMLBzcDjoT144pvtybJu93uSl+YK+6JtHvQ594TgHnclLB6dj1O3aAmXGNI92pGwg4M3ECeCX1IZDBVa7JWbIkLx8YR8OxoOX5qD/smv2Boe2OR4c9E235/QHh5MX44POoNl52qQmNalJTWpSk5rUpCY1qUlNalKTmtSkJjWpSU1qUpOa1KQmNalJ26T/B3VkC3IAyAAA
  values:
    replicas: 1
    priorityClass:
      name: gardener-system-100
    clients:
      - name: local
        clientId: local
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller
      tag: v0.2.4-dev
    imagePullPolicy: Always
    webhook:
      namespaceSelector:
        matchExpressions:
          - {key: "shoot.gardener.cloud/no-cleanup", operator: "NotIn", values: ["true"]}
          - {key: "gardener.cloud/purpose", operator: "NotIn", values: ["kube-system"]}
          - {key: "kubernetes.io/metadata.name", operator: "NotIn", values: ["kube-system"]}
          - {key: "gardener.cloud/role", operator: "NotIn", values: ["extension"]}
      # TODO: Add the moment there is no single label key to identify the components which should be
      # enahnaced by the webhook. This setup is not recommended in production environments.
      # For production environments, there shall be a single key on pod level and each component
      # shall have it own value
      # objectSelector:
      #   matchExpressions:
      #     - {key: "gardener.cloud/role", operator: "In", values: ["plutono", "prometheus", ...]}
    vpa:
      enabled: true
    configuration:
      oauth2Proxy:
        sslInsecureSkipVerify: true
        insecureOidcSkipIssuerVerification: false
        oidcIssuerUrl: "https://dexidp:5556"
        scope: "openid email groups"
      kubeRbacProxy:
        oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVTWpuc1RhZXNUbW1JejlFU3RuM1QwYjZ6N0t3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd016RWVNQndHQTFVRUNoTVZaRzlqYTJWeU9uQnliM1pwWkdWeUxXeHZZMkZzTVJFd0R3WURWUVFERXdoTQpiMk5oYkNCRFFUQWVGdzB5TkRBeU1qSXdPVFEwTURCYUZ3MHlPVEF5TWpBd09UUTBNREJhTURNeEhqQWNCZ05WCkJBb1RGV1J2WTJ0bGNqcHdjbTkyYVdSbGNpMXNiMk5oYkRFUk1BOEdBMVVFQXhNSVRHOWpZV3dnUTBFd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERHcwRnNOMVhuV2JNOWpybndYRi9jYVRvTApVUCtuOXVTTUc0KzZDdWZ2cE54R3lBM1lHbGVUZmZpOThyY1MrUXVCTkdzSUR3bzczQ2c5SXBzSEFZSkZlYnpiCkREY3NTZUIzUytaVkNqZElHTXYrNW1WbXlTT2wvWGJEczF3TkVLSGx3dCt5am92MTIvSHpGQ3hUd2RVSjN6bG4KK2M5REo3cmw5R2FsTWtVZ25FZG84WkYrQXl0SFhicEVnaEdJRVhQc2M5WTZ5THVPRkZQZXd2TXRFaGxnT3BPRAp3ZnhKZVlGL3pNblRBak9CWEkvUGVYdUNjTEwvZFpHTGJkQ0tBeWpxdTV2ei9HVFJiSHd1d0d1cWljcTVUUGJ1CjlFTkZFR2ttNDJYdzlCVTJXTm9jc1RLdnpZYUEySmp1SUo4SU54YmpMTU5Wc3g2a0ZKTGQxZTVrWWJCbEFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlFtZE4wL1lhd0E0VFk5M2pKcGxSWW9rRnJKaGpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWFNdWxldkE4CkZjWXlPakRjZG13M0xhcHBmOTA1QWg0RS85OXVzSm05Mldab09qSnJaOGs4N3JjaGVGTTl4bkJyZHdtSFR1TGoKb3daUjdla3MvcVJRTk5KdG5ETFJaK3lKWDhQekYrVUdpMWVYUmF6NFRsK3JtY2RvaVVoOEJya1h4bjk1ci9QQQoxTUFHcXNJMFFoK2tPdkNGdUkrcUdHb09QbFJwQ3VCbHp2OGt0Q2RTTmJtam4zTEwvOUluMUF5TlB1Qk4rUmhpCjNpL1I1ajJPU255N2RDdWNxdjZVcmJ4SXcyRDh3NWs3QlJQUmxydE9WY0RmaG5tWERwZDZNTXIvUmNpZGh6aE0KN3h2cXJvUjBHY3pIUElzMW1ETGNMVlZXbW1WeGdUaEk2VzhQMm5mRXNzbE9BTW5aWVN3ZlZGVS8wQjNRVjlJbgpLS2N4dWIrNy92cUJ4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          hostPrefix: pl
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          hostPrefix: pr
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden--plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-seed"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: prometheus
            name: seed
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--aggregate-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: aggregate-prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-cache"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: cache
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
