---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1dW3PbRrLOM3/FHGi3YmcF8CKSslmVB0XSJjqxLZUoO7u1teUFgSGJCAQQDECJUXx+++meCzC48CbJsuLlVMqhgJme7p6eb7rnhtBzHdOOImY6YZDEoe/TuPnN46YWpMNej/8fUvn//He72+v3+u1OB/O1D/qdw29I75H5qE0pS+yYkG/iMExW5Vv3/k+awrr2t6bUn3mTIIzpY9SBDdzvdpe2f6/b4+3f6nUOuvi83Tvstb8hrceofF36L2//PXJhJwmNA0aSkIg2JzdTGpBR6vmuF0xIZDvX9oQyq7FHrqYeIyyNojBO4AfYiU8mfjgiMztxppB7n8TUtxNvTqFcMtWe24ELBAI6gbdhQF5EMR17t9QlNx7k+5+XFjkP/AUJA14SWSIRjYnvBdRqWCfDj8MEeAMSx+FsBgQ+HA+J68WsYU28pMn/Few3rNHvcZP/qx5MJ038R/3J5kEzJzQC+dKIjD2fssZ3FruJ4N+RfQ3/JjP8HQKdxnf/ByU+2LEXpoycnZxCvVEc/kqdpGF5LrWbIjs8alhz5oQubTZGXtBgzG986UZekWr7//HUjhNrYc/8R6ljTf9vdw4Oy/2/1z3Y9f+nSHbkfaAxgx45IPN2I7BndEDqjKLhUubEXpTwrEfkJxgiiIOGQsZhTH5OR9BjaQJdSMEE/JdMqcwzF5VY4pX8iwTpDIoBjoSp75IRJV7gxHRGgwRwgdrOlCTejJJFmAKQXHNaASAR1ABglRMHaCEe4FFCZxGAD2X7SMhPOXxhNpAl4wC7sfjJiA1gR28j6MRQH5Acg6jhDRnSmR0knqMyIpkX0ySJ2KDZZHQGpAAUJs2XjbnSXctqWe2y6CUxw7FixvccgYIjirRdGvnhgrprtAPUN9OP0o5Wk1UUOggTXXCgvFx05IouFBuA2j4UK8hXlgpkSBmWBLpnCf4ZUwfAlgau0HPKoKkTgfy/pWGCgwsQyCzRmHN9Gs8ZOb+OVIv/buhYk/DR6ljn/3UPy/5f97Dd2+H/U6RmkwwvTv5h/h28n+MwWoCrM02u6G0yIJ1Wp02GRxdkeEoA4e2A/2GPwVHyAGQJ9OjIDhYcfX+0Y5cGAFbcirxRCr4aazSbDUX/jefQgFHzDLIl3tijMQwi4FlOqdmxWg3INwkHEySBpNmUmA4xLKsJ/03BP2uqV5qZmjGdeCyJBb6xqYFUwJ3l3qocGWhgj8CtIwXiwn3lw5Z8qMYJJ4xjBLe8ElKopBHp1L8GdKrt/9k4+jgzARvG/4edVq9/0O+i/9fv9Hfx/1OkNe3/ESI8iMKYlUT3jwXW4P9hu9VT8z/9g4PON60OWEBnh/9PkfZWwX/3YfC/19jbCPxN02zc3TW/a5zeRkgNkRgDEeUwc7C1Gt81P32CfCa4y2MvoMTIbRcYhgoQobGcQcw8p536CbFERPsOiVofbD8FhxNznoMHG0P0Tv4gSZwGDukf8J/ebJiCoLfEMA0iaYHzij8Fp8cxRR3YWQ3j1PcX4MvaPsrn8ogDa7Aav1BBm+dPsAaUh4E/79joB7MQmMrDJyE50PBd4ar73syT4UmC0cGL0YJr5eTdEPPi0MXAkX9pNc7GOPlCbSbVh41he+Dxi7GQP+Net+9jrAWVA59QCWdecruRkjF/UdHeONOrepnpVmZZ+n4T3fsso/MXLsfg+80bN+cx04ggYl0KdYmyis/Cwy2Zi2IvSMbE+Csz/8qMEi1R6eamVv+zYIBay2LPUQGZzUTrSlMRuXx7RP0NW5iXyJu3LJaucfFbhm4gUgzBrO0A3b8ZxPhobN+1xKwc55Ztxq3IK9jFqWtwBptcggG5u5NTAasFtQQrq/MyipFvGL+R1VmaZUk1HGVBLL6D8tZ11rMtL2xm8wVQV7XIHyIYLqmlSgVCdHBCXXO0EISUlQ1pPAeorVXrUDK/lWLLEpu17IhJo3XaE4Bh1UsEfTKxA4cW5dG7ZdFGaIzjCMfUbeRx8nK6SOtY9/UGrzKPI2EYwNA2IFoFS/tsZXjThGHUiWkip0i2lmnIS79bhsxaTssRvChMlViaE0CALXf7FyuVlA8K1kti3NDRNAyvzcQHz5LqWKJgu6bOOkZZ/roGbxUxQ/4AyFmBopVm0FUf0zGNKdggDwz5W9v0gl95B9i6KS7puA4+m5VRgUUIlqtVC69YQuPL0KfvlIbNNaLpFsYkLtiOE6bBduYlyx6Jokttq5itZF6qlbYwoCV0g43tYBMC6w2k0E9FKxAIkuh2PbTcfF+5/i5pkuKCog0q8wAWz7gjwig4JFh8Qx+TJs70WJb/YTGE0nn4wPs4IRy6RB0KsyaAnor1iYxKLKzasoMgTPg0DtNqtLIatfyOH6ZuUxA2hUrL9Z2dYG2G9iLGqfccwnguJl6LDNDa9DciNKhzLbOUyX9PrEx9ZiHPCIzjOnumqb/mj5j+lnoxaP4FByFijKEZoR1CklWEcIcaGhBjieo4yy813krg86WD2F26d1oz/6OPxPdeD163/ttrdfP5n04X538OD7u7+Z+nSM9n/medqypij3y1GrOYIhKKeWjVblx7AaCYFhw0ZjSxXTuxBwCHm4Up2igqUDRQTlo1NhG+G88lQoRBDvYr/blqGGJB8BcA+6Ag0kWSOKeD5NyA8aoEaXNL/i02d+5X8O6uKurnoaf8I8sPHdsH6h5jKbhLdCxkFq16xh/yB5s1ZNVpFi2VBxQb0KiPrayi2/Ol+/BD0ub4L1rlPqPAuvXffl+b/8d8nU6n29rh/1OkrxD/JVL8+aGfUX889CYBuuZ3nwlw1vV/AaIY8n42/69z0BL7//qQ6eAQ1//akH/X/58iPdf+nw/ey/p/PLIdy06TaRh7v4vtGdevWNETzKncAw6WORBb9Xd/WSePU184dSYBqX6MwzRiA/IvnFL4NycdUxamsUPFUzkNw4x9Qzgw+IvOcY5BFZjTeCQyfycelSkja/XUxQbEGacGFSSgbwBDxmshBq7oAGLxPzetK6DJTRhf4yZA0Sr1FcN7eMDo5oTr6WRIzRmOQreG4IQmIJzvMfzfDe5Lr6/BCcPY9QLdpOor5aPBppwbtjsDFwpoFnYUSfpV8sYsTfjGJDmTDj1r7E1SUYwZGwi3b6QRWDxdYgzQRxn42+taaI4DFuQDnaoi0AM3FXrp7FqdxLLDbSQcr+zrcMG/aNp8/B8BeqGxbO8GrN3/3z/M/f8e9/+7nd35nydJz2z8R2IrfIDVqyUP8xB+EPb9GHHDI3kIwJScBFGYukKmhpoo0Z2eh7k6LB3h6qf0UgT1YUHz2nTM2jrqFhIttfixWaS1w/tHT+vwX/c67hsBrsN/wPsc//stjP9wGNjh/xOk54L/pXNoCmww0vkTz+QkiwiP00X2byltgM8P48uJFCTvbrxbDcgfvNpChxtoi75J+E/Ilg+Oej6t2r5CVLBqcJvZChIyBymV/tIWuUtPmdbgfz4x8IDjwKvxn8/8yfMfh+12l+//7x/uzn89SXqO+I/mmLvoJ5kJPtOBYKkDj6WnoFDTntse5ALFJQtTILeVzXyUtx2JMQO9ZRpnSwFqCo5zrTZrdTIoV6/VCqfYtSv45zcwvNEE2kCk6k7nygijMEJWorUMJm2zlXoEY9uUOtcsnRW9ykIjyl1Kf7GuJHnrB2ieC7xJwqhxRo2XnDU2tTu9PlDO91IJIfkBY6WkKHSPtD1gpaxqcNQkfVXOk+2s0tSYz1mDDmLPYZY4czh0YrDpYKIXiOIQMk1pqm2bNmo2PBtLSjCkiWWSOKXLMuHZRkm2xBg/9ahTr8jkF8zkgYZSUJ82H1y299B0wUqIjefPqbtZCTCTOZ4GlZm2Lp6OoL/ct3QM8as3o6ALT3TTYnnVZ2uN0JvZE3oBqCR8W80My28GW5hnpSGrwfZ6rFwZoEOXBlCf4ZviFMBVeE2hD6NFZnU7aQxIdwxjAY4ktXLkfXJYzL5cwNL0EJhAyMv5NmP1T7PdqqqfaO8ynawoqZ3HWKJneaAIRq5cTDMfm/SDMlpnWKGjJXpiS5XU7hQpczMq9n/+CMeIkHnQVxdQYFB5ndgToFo6U1U4zmKUa0FjvQihIy0KihT0ouxlkT8azIvSKnW9O3p7Orw4Oj4tvCVkjlT/DhA3KL0g4pRctk+o5h0OHINscLKywb+ibg3GOfsfOKrhCbIbUHup8XKez94e/Xj64fT46vzy4/mH08tfLs+uavkfEHEgiX0MFc0mr0h7wEe0CmelMaeGYQVQy5j88ejy5PTdx6Pj49Ph8OPV+c+n7+pZNJpzO24CujXlEmOzhH3iz2YOHrYDDgwzE8QAY1Xlw9PTk48n52+Pzt59xIZewoBmRcUdyIipllwstNxwBn2uZJHF7dMu7s5e7Rmu3l9uLVF6XsFqbXOBz4/eX/3U+Xhxef6Pf348fnN2+u7q49lJvewg+lLaK+yg8hiCeqb3B5MYpvm7HZkunVP/+6LnoL32w4np8yydynvheH3fBJU1S/MWlbwp+Pn61pzvtTatPYBUoaCODmFuZrpeLCqWj5dmR/V/v108sJQWeko643JoFB7UHwRd1GLpOgypHeVVZu4UvEAMv11eqvWyWJDzKJePF6bopJzNoOw3LjGOpQ+3cmMlIzJjRVkFd3OZsipc+N4cujtjF3E4okVAx5uXfqRJGeUjDu7NKbX9ZPp7+SX3gl+1XrVLLxhEIdhPf7q6uii88gIv8Wz/hPo2oAGYuQt+Yb9VyBNRcBLc7G1bfwv27Hr3kgBLLj6TAL1GkSSrH3yl4Zeqyrybi1CepV3ZIcoSxGESOqE/IFfHRU7vYXE5qzL3xqzWmuNWrFZsNd+1sM5vy3Ku8NjmoZ/O6Ft0piutwx1u4cXoIFhiXyiG4+Wa8iX0rqejh9ll40tHgtoqQg9wqDKkNnmpOS9lZi5SiRtduop7VcqLnQwvmCyEKjm/D3ez6r2iFRw/xNlazX8l6gxCl2YHwLNs+tMHRZuV+nCWENBIc/3Vk8etJwl9Gpfnc7SHD6otCaMQvKLFMELbgcgLN215hU4KHcy+HV7TGxgLtCZRJX+mYG7Fs+LTkCX8EGSeG29bfR8w4JiNPUTAARkCxrupT4+CxY290EdJnGepthk3reo8ny78vadx2t1cJQKqamLdIvZsdO48Z0/eo0rdIt+1GItVig5TF/RtuNthxakOXQR1QDanT2dRsjjxypqnrpfOBuQtnUF0XSRRhBVzDcTWSbbNeZXKdHdte6wD5O3BWMjz1o6KrN9njn4D4JeTFG8Bvgak22mt0vgGIL4xgK9rnTUEnuWB2TXrf1pjfL7zn61eP9//cdjm+/87u/t/nyStXP974PWPD9j/vwyiareJHCv0efAC4VLw2X7Z8L7X5NRA+LbX5SgN1E4w4kaT8mRtWdEYJeXLmM8St3bpcdIa/I9C1/VYnPJrv0epO6H32Aiy7vznYVfb/3fYw/3f/d3+76dJz3H/R8SXjfIdIBehe5IZ4Q/cCJ98K8gDtoGo9WAIFd8HcisIBnkYMT7BVo3V7b+u/8tFUYcvin6m/b/tXvb9n3631Uf/r9s+3PX/p0jPpf/fc4E/n07QAYSJ6ZP8aJuGJXrxehRZt5VgQy9Pv4r0vp5cvjaY3eNk1LPHc4ovLYiMxhI5REagjZ/twdUCHksPyNj2GS1+5MNQyiK8+2f34mWtnaFQncCWsfMcn39ag//ZYiN0NN55wUq2HgbW+X+9w9z/67YPuP/X393/8STpmeG/whA3dK5pLAL7/2XqNt1tjojkhg02jNa7occntt8WQVpwIyY5fwVusgjbKr8pAGGdEM/tCNua/o+bb+RGg883/9c5OMj7f6fF739r7+K/J0nPtP/r8/T37felSfgvdAQMCS3d6x+lcRQy4IgzaaLvRhleN7yyFPfGBkQ8bdRstpe7M+R1v8uPGsjFKOgC4cys/ejbNtRUpPztnXa9apn1jLQxELvYP30rIfdcnJJ7bgD5lae1+C/2+TzoW5Br8P+g1T2Q57/6hy3u/7Xau+8/Pk16Lvi/BOS59f35zn1VEFk7T7IUP8cxoDDk8l0Tj6jwzXrk23/dGWp3GkDm1fGFsW/gO2Nwd1e3G+/Tp0///jYXYNNddhszaPu+KbxCfhjJlKeITXkCZiu+9a15Od8bsyLmib9gzVHomtwKzGwelyzRT9Yi2v6ETarL7DarQoqozRWDYEbpAyH6iQdQgiBqbCVoVTgzZ8YGDEBG8vudkHBlf5YyTLt87g76YM1urG75mo9s7ly4CDUbUPGFKKXtbjXl7tkNN6yKJhIbR4sbLOv2hVY3zG7V0Wp4W7VDdTkH+j7YgmEV1xQetIDQ3U3dfeVpM/9P+f73cwPX7/9pa/H/Ia7/9A52839Pkp6L/7fR51DKF3yVHUV1K9X2/uKKs69P6zkuG0KVJiojacXVXLLTuTq2bnCgd7eA87WnNfg/j+yHxf6Y1uH/YTff/9k9wO//Hh60d99/fZL0TPEf7U74z24J82surm3O24YcCD7I22ovQvcou632zzZ/kAU9PC7JzrfXXZGDzyvX5OQxwtZiVoYfbAhxjbB+mF9/Mtg4mMuntGVJzql2cg8eevmBDzN/lZ1++MuSGxUy8HIv687mAakoLfw9q57VqMg984IjMbegV5U/XSZ5u7XBxTHV2uzbutqyp1vXttHgvQb/ZZj7Wed/u53WQen+/1Z7d//j06Tngv8FcFtxU3q+k+utvB/9F2Gix4UjVc/mEt8aB33pjJs3CcK4eL3Txifpyl9DER8uNR3bxAnLrc7E8U+XZocPNBSRYCDvA77X+Qq8mb8ktmCf33wh2lABt4x8chy/9wEKVXj9AC4n3cQBXU6dX8NPzXkbec9zbDO/6Ng/pIHrS0myDz+IgSiMssOqeNX98eXp0dUpfsTg/cUJ/pIX7UsHoOZDCPKN7D3y0v62/rZ4ob/+cYTKQKTwPuQ3P5ePDBefrgw3+zX2s7LGrH3KlVZe3Kte5rn0dDzm11mTd2FAz4OTeHGZiuN5GeJc0rlHbzJdZq0kXa2YesE8dHh7Ke/nbPyOUpfvL7pnp4DR/0/bKYD359Qpln/VYttusvq7F7uO83gd50u7QP/Vqdb/nwsLe/DEj0yr/f9296DfUff/9ru9g29a7T5eCb/z/58g7RF5AkDcQyY2+deNII2GuFmQR/HqJsEBoWkMYG2Kra5WdD2xXDrPrjIx5dUOzViMLPklJ8185bi5ZOdZpF0vCFgRJheA0GJ+Y4/gYdUYoInxEwmcNYJXGN5MQ0azaww98ZrfDYNzJhKfLD65MgFPe96y2taBIYXTb98k//p3AxFUVQSZjYYaRgsPG7kOs3t4+Ux6dmCiTkCSX63dyG/37TQaxQn/AZd2GFEH4yaGl4UARQjHlCdA5NocYdMw9V0yAnF5ZIA+hPiVXXmzR/QLcJMQ4NvF/yGPJXKlwAW/P4jlryAnP98RjutKIbEUHAie92xMgABkSXiMKOMVbBLgZh8k4ITg7wkaBHIMZXGlHAkrTWf3DGeBHGpci1aWK0jLVFUORlWlmAlZiYSJgasiDEd8F4VX8cuUBuKUzP7yRhXU2T6JUXXADkouZsuEKcpRW2eOWVpLiWM4daouiMON9B7aThRReCE7Cc1MINM59zOM7Da8xGf8Mj6DsBTC/9tG4doLaI386zErWkNkIvhVm81staIAncLnN7RGo3hhNO8DjeqFtfz5Hhkz+YWeDoxp2IvrMjl2JK4B59Oce+AYuQCf4pdJjt68gV/qoqpLGHBwWoYtQOqZ1Au8ToMjBn4Yvi4+fM9wXqUtq8/CBLF1Rn4V6Oyiofz0dqvTa9V080bhdjPfm3lqW40TpVy8Gf9LzKDCg17/rcdHBb55Wc/bLudtd15B3obcuoI5i5tkstbPbr8DWQrn14SBVXuLPCkHNfI/y3vBtYGlASFLXrOrEylMa/Mnaqpb3DVj4JqCIV+Aw+sk3PPlB+74xxNVIWzN4qftohTDF6EH/n27PRl1wNgUTKhGZECu+Lz/T94Ees4VvL6UmuWltOlnSYWrusc1vafput/lzbKnTyHrJWRD7lWaslG4FwxNQr9RC8fF7DIvbi8SJpB4Kc4Rowa0RTEM4aVgCD87OSZH0DrkVPkCpDiLt6fM1ryBwTY/bsjvG2pUPpUiSV7E4Ryyx0VieEk8np8cLXCLnvo8Sh3Qg7LE7cEwjNsBgpS6QQOq5+WxfsQ/Ksmg5PhNrg5UfSuXNSQzQwfcIxFI4S+wIfg38FxCZ7Ynb0+VWUW4T85OSqwK0rgT7BYhtcjxPmaGTE4Yg8FFYZChOdg9OhWJ0leuCUkBewdS5crSJhzOXD7IVjmTo86X4m6PAMIxcvHz8aniCOvGKWVJCG9SU0OBJpBw6cpCgQzQ45yEvL988wVlGoYw9nCG1AsGw2zEp0xuPN91wGFm/AJRNmg2v7Pw+w/8/mO5BNYUzDYd4GlkO9cy3BayvY/9stiqFgLvcrW6BJxWG90fGN9RHuuG+r55HYQ3QVNYrFkUyfXAoKFfLPjEkJjlAPHEx7f1ehnzzwI+HNLhtYcuuDde5KiL95aKt+dQHHMIEjyf1Oaq3DAUOtpIgPtgL0EPhZ6IDwUYoNPAmxkfmfgxPQxRbhcosvQbhuKrd0f89JCY1iDqg3voNHiBE87wR5zDMocNIj7wBC1t86bzETpmdozmIpwsWxqkM3MtyY9qWIycJiEPnuRCh8hqTsJmEoY+a2ZFmzBUNuftPUGB154LOExircWPgMkxjSmoSNQvu7BcWEVusai01ixe+RmVc/nDEcdSUE6NSlgOfdxXw2240CPovG2J7naZVaxEnIBXmY4s0F4z363MhRn54agJoVjnlQWGDFRAPP4dFAY62XvTbrW7mZgZdRxG0Pnjiybcn9eaOXflJYPoI3rCF+XuJEaJPBPvDS4Xu2wTKZNOuxAVnBL3W1YJlDJVg+vC0Lc8PiIjPrWJ3T6iM1TrDEyCmx60wpz3gCx8Ao48vi6WLJA17KRZbzo+kpOkepPKNuROumNbDgDFNV3ki+WC5TIzT9pQgvcVTaULV2msk5Rbaw07o9gOnN+bpYZqeogYrNnpvSb8JzdkgC5CvWKLJzc8yrOhWwbg1uG3EEJ+2UFDjPwuQC3ExB4+sn25BKjgPbeCLFbAvp9dEPOploZdjLhXECo54g+iJaIneVF+recDmfJxBIId7Xtxe9IDJfKiUrmsoSwof5d/S0EaFi67gmG90W8pXQFxYFIz25mi0S7wNT5g/PAC4luByqoZ7Ywn0RRPyFDNdaxC8+Af20rVEELAyEDtGY9q9knI0RgyyQGEW2TuyOBYDD6FGnKoa3G62iGF9fXIQwPkBYq6z+V9qUqdn5wPhD9Tdo/BOJTngUaHQ1mGIvntH1kt0CFnaSCHaJ1HdWSh2Djy6w0Qd+F9ElHoye4un6slAxXa7eVDvkYEfTXhpOzzIRt0CbkDHLdlh8iNeh+BBr3BMo7f3aEhffpkih/corJ1Kbyg94LXkIGuVj++zTShJIJqXG8MKEpwrZ2/urvL6Xz6RP4GD3LGCnUNylUoqnpnL9dYOqGbt6tqv2DiBbfZBzOKh4PQS6SBa+ZHSwy8S35ooA8oJ4W4dsE2IUT22FT0GKVh4XDKMRKXh8BFlWxUpwwlc2+G8sQ2FwXUhOEEA8ulMfhS+jW4ic/ycSMjcB5JCJRNyD3p4vfAsrxnSRawyXZXM0c8iry7K5TLFySL4SQEn2fgxtuMzz+pDS7g/FMKoDwDglkJCoGH50y1AA40BV6VGPB5/fwFGpvV4B2XOxciaMhUxkfx/+RHp/MZ8uoBcO4aIr3/AD0Ie2JBLLsFCP/wwwkuYJbm0LCk1RD/l2ivlq2h1jb8+WZFOTl/kMWJ7dZBvzd+5Zju65Ftdrvj1+Yr+qpnHnbb9JXjtNrj1w7O16gPmwiUGdE8HJK6gYg4UyeAX1IbLxVY7ZSYIQPy+pV90B/1X5v93uuO2e0f2Oao3+qZbtfp9Q/Gr0atdn+3kX2XdmmXdmmXdmmXdmmXdmmXdmmXdmmXdmmX/ovS/wMKuXNaAMgAAA==
  values:
    replicas: 1
    priorityClass:
      name: gardener-system-100
    clients:
      - name: local
        clientId: local
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller@sha256
      tag: 1bb582474526ef4f253ff26748e25d73e0223ae786261f8b723e2977b46906be
    imagePullPolicy: Always
    webhook:
      namespaceSelector:
        matchExpressions:
          - {key: "shoot.gardener.cloud/no-cleanup", operator: "NotIn", values: ["true"]}
          - {key: "gardener.cloud/purpose", operator: "NotIn", values: ["kube-system"]}
          - {key: "kubernetes.io/metadata.name", operator: "NotIn", values: ["kube-system"]}
          - {key: "gardener.cloud/role", operator: "NotIn", values: ["extension"]}
      # TODO: Add the moment there is no single label key to identify the components which should be
      # enahnaced by the webhook. This setup is not recommended in production environments.
      # For production environments, there shall be a single key on pod level and each component
      # shall have it own value
      # objectSelector:
      #   matchExpressions:
      #     - {key: "gardener.cloud/role", operator: "In", values: ["plutono", "prometheus", ...]}
    vpa:
      enabled: true
    configuration:
      oauth2Proxy:
        sslInsecureSkipVerify: true
        insecureOidcSkipIssuerVerification: false
        insecureOidcSkipNonce: false
        oidcIssuerUrl: "https://dexidp:5556"
        scope: "openid email groups"
      kubeRbacProxy:
        oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVT3B4dzVnS0MxdDdYdW1abVVzNENIZW5kek1jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd016RWVNQndHQTFVRUNoTVZaRzlqYTJWeU9uQnliM1pwWkdWeUxXeHZZMkZzTVJFd0R3WURWUVFERXdoTQpiMk5oYkNCRFFUQWVGdzB5TkRBeU1qSXlNVEUwTURCYUZ3MHlPVEF5TWpBeU1URTBNREJhTURNeEhqQWNCZ05WCkJBb1RGV1J2WTJ0bGNqcHdjbTkyYVdSbGNpMXNiMk5oYkRFUk1BOEdBMVVFQXhNSVRHOWpZV3dnUTBFd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdElNR1R6cnN1cUdCbXByKzdidVdEU2o1Lwp2T3FwbDlwNWhsTWNUaWR1eHFpNmtyc2M5VWZDbmRKeEUvV0hDZW1POUlqWXRTVWtBeUtvSThuZjVTVlN3Q01rCndVZWVmVGVnK2laVUpseXdvTitGWHZUL1Uya2lYSXRDV2hNUUwvWmdjWS81OVROS2FCekdJZkY3MVY4TjVsM0kKSkVTbEt2UFliMnZvV2pYNXdiV1JteEkvSElTaEhaamhBK2htSkZBM3BBQnBQZUFvcmYvanB0YUxIdFgwQk44Qwp6N29uMmdYTzdsUVN2Sko0Y2F0SHdXeFRTQjhPRncwNXZiQzBTaVlmVVdUSmc0bFJucTZhazhicDFBd01TVGpIClUwMGJzU2ZXL0syeVNmSVhMMENHdFVvbG45K05icjdIU3ZvbHRYaXp2MWd1UHR4ZFV6V2t1ZGlqc3prckFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlRIZ2lvcjhzR1hweHExTCtwblpqRS9wNTl2M2pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxBZGVwZjZICkFNSjFMOWliT3JONjV1RmVISFJPUTZTR3BjUURxdXBqUG1CU3Y1SGJsb2kreTlWalE1eDQ2dUtRdGoyTWJlTGUKVGhrRnA5ditsYkk3U3JqRjd4R0tOckVHcVJzanJzdGhmb2FDdkZQU3QxMWEyd0ZGeHdsVmsrTzNPWmNhRERaRgpNbXdGbmJmbXB2bHpyZzN4U2wxVkdnL3BiYmVzTGJoNTNyQk1ndldkcU5JYUtIWExoYXJSMXBYb1A3NjR6czhECmFQcnc4bFNxaXZqWXJJelZVUzllUDQwQTJLMU5vakJQVlB0dldXMXpySGMzb1c5SVZOS0EvaXFnMGNMdzYwN2kKblJ2NXdDcFlKTThKTDVYZEZ6N2NPTXNNUEUxaElYU1RDUnB6QnFZeUFFV1hEeXl2d1RmMHJBQmZzTDlzUVVQRQpYOTZFVVJsbWVsRW1nQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          hostPrefix: pl
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          hostPrefix: pr
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden--plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-seed"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: prometheus
            name: seed
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--aggregate-prometheus"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            app: aggregate-prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-cache"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: cache
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
