name: Unit tests

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'
      - name: Perform the unit tests
        run: make test
      - name: Perform e2e tests
        run: make envtest
      - name: Report failure
        uses: nashmaniac/create-issue-action@v1.2
        # Only report failures of pushes (PRs are visible through the Checks section) to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          title: 🐛 Unit tests failed on ${{ matrix.os }} for ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
